/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Unauthorized
 */
export type AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBodyData = {
  error: "AuthMissing";
  message: string;
};

/**
 * Unauthorized
 */
export class AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody extends Error {
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBodyData;

  constructor(err: AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody";
  }
}

export const AppBskyFeedGetFeedGeneratorsError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
} as const;
export type AppBskyFeedGetFeedGeneratorsError = ClosedEnum<
  typeof AppBskyFeedGetFeedGeneratorsError
>;

/**
 * Bad Request
 */
export type AppBskyFeedGetFeedGeneratorsResponseBodyData = {
  error: AppBskyFeedGetFeedGeneratorsError;
  message: string;
};

/**
 * Bad Request
 */
export class AppBskyFeedGetFeedGeneratorsResponseBody extends Error {
  error: AppBskyFeedGetFeedGeneratorsError;

  /** The original data that was passed to this error instance. */
  data$: AppBskyFeedGetFeedGeneratorsResponseBodyData;

  constructor(err: AppBskyFeedGetFeedGeneratorsResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "AppBskyFeedGetFeedGeneratorsResponseBody";
  }
}

/** @internal */
export const AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody$inboundSchema:
  z.ZodType<
    AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.literal("AuthMissing"),
    message: z.string(),
  })
    .transform((v) => {
      return new AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody(v);
    });

/** @internal */
export type AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody$Outbound = {
  error: "AuthMissing";
  message: string;
};

/** @internal */
export const AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody$outboundSchema:
  z.ZodType<
    AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody$Outbound,
    z.ZodTypeDef,
    AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody
  > = z.instanceof(AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.literal("AuthMissing").default("AuthMissing" as const),
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody$ {
  /** @deprecated use `AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody$inboundSchema;
  /** @deprecated use `AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody$outboundSchema;
  /** @deprecated use `AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody$Outbound` instead. */
  export type Outbound =
    AppBskyFeedGetFeedGeneratorsAppBskyFeedResponseBody$Outbound;
}

/** @internal */
export const AppBskyFeedGetFeedGeneratorsError$inboundSchema: z.ZodNativeEnum<
  typeof AppBskyFeedGetFeedGeneratorsError
> = z.nativeEnum(AppBskyFeedGetFeedGeneratorsError);

/** @internal */
export const AppBskyFeedGetFeedGeneratorsError$outboundSchema: z.ZodNativeEnum<
  typeof AppBskyFeedGetFeedGeneratorsError
> = AppBskyFeedGetFeedGeneratorsError$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyFeedGetFeedGeneratorsError$ {
  /** @deprecated use `AppBskyFeedGetFeedGeneratorsError$inboundSchema` instead. */
  export const inboundSchema = AppBskyFeedGetFeedGeneratorsError$inboundSchema;
  /** @deprecated use `AppBskyFeedGetFeedGeneratorsError$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyFeedGetFeedGeneratorsError$outboundSchema;
}

/** @internal */
export const AppBskyFeedGetFeedGeneratorsResponseBody$inboundSchema: z.ZodType<
  AppBskyFeedGetFeedGeneratorsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: AppBskyFeedGetFeedGeneratorsError$inboundSchema,
  message: z.string(),
})
  .transform((v) => {
    return new AppBskyFeedGetFeedGeneratorsResponseBody(v);
  });

/** @internal */
export type AppBskyFeedGetFeedGeneratorsResponseBody$Outbound = {
  error: string;
  message: string;
};

/** @internal */
export const AppBskyFeedGetFeedGeneratorsResponseBody$outboundSchema: z.ZodType<
  AppBskyFeedGetFeedGeneratorsResponseBody$Outbound,
  z.ZodTypeDef,
  AppBskyFeedGetFeedGeneratorsResponseBody
> = z.instanceof(AppBskyFeedGetFeedGeneratorsResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    error: AppBskyFeedGetFeedGeneratorsError$outboundSchema,
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyFeedGetFeedGeneratorsResponseBody$ {
  /** @deprecated use `AppBskyFeedGetFeedGeneratorsResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyFeedGetFeedGeneratorsResponseBody$inboundSchema;
  /** @deprecated use `AppBskyFeedGetFeedGeneratorsResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyFeedGetFeedGeneratorsResponseBody$outboundSchema;
  /** @deprecated use `AppBskyFeedGetFeedGeneratorsResponseBody$Outbound` instead. */
  export type Outbound = AppBskyFeedGetFeedGeneratorsResponseBody$Outbound;
}
