/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Unauthorized
 */
export type AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBodyData = {
  error: "AuthMissing";
  message: string;
};

/**
 * Unauthorized
 */
export class AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody
  extends Error
{
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBodyData;

  constructor(
    err: AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBodyData,
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody";
  }
}

export const AppBskyGraphGetActorStarterPacksError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
} as const;
export type AppBskyGraphGetActorStarterPacksError = ClosedEnum<
  typeof AppBskyGraphGetActorStarterPacksError
>;

/**
 * Bad Request
 */
export type AppBskyGraphGetActorStarterPacksResponseBodyData = {
  error: AppBskyGraphGetActorStarterPacksError;
  message: string;
};

/**
 * Bad Request
 */
export class AppBskyGraphGetActorStarterPacksResponseBody extends Error {
  error: AppBskyGraphGetActorStarterPacksError;

  /** The original data that was passed to this error instance. */
  data$: AppBskyGraphGetActorStarterPacksResponseBodyData;

  constructor(err: AppBskyGraphGetActorStarterPacksResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "AppBskyGraphGetActorStarterPacksResponseBody";
  }
}

/** @internal */
export const AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody$inboundSchema:
  z.ZodType<
    AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.literal("AuthMissing"),
    message: z.string(),
  })
    .transform((v) => {
      return new AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody(v);
    });

/** @internal */
export type AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody$Outbound =
  {
    error: "AuthMissing";
    message: string;
  };

/** @internal */
export const AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody$outboundSchema:
  z.ZodType<
    AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody$Outbound,
    z.ZodTypeDef,
    AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody
  > = z.instanceof(AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.literal("AuthMissing").default("AuthMissing" as const),
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody$ {
  /** @deprecated use `AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody$inboundSchema;
  /** @deprecated use `AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody$outboundSchema;
  /** @deprecated use `AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody$Outbound` instead. */
  export type Outbound =
    AppBskyGraphGetActorStarterPacksAppBskyGraphResponseBody$Outbound;
}

/** @internal */
export const AppBskyGraphGetActorStarterPacksError$inboundSchema:
  z.ZodNativeEnum<typeof AppBskyGraphGetActorStarterPacksError> = z.nativeEnum(
    AppBskyGraphGetActorStarterPacksError,
  );

/** @internal */
export const AppBskyGraphGetActorStarterPacksError$outboundSchema:
  z.ZodNativeEnum<typeof AppBskyGraphGetActorStarterPacksError> =
    AppBskyGraphGetActorStarterPacksError$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphGetActorStarterPacksError$ {
  /** @deprecated use `AppBskyGraphGetActorStarterPacksError$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyGraphGetActorStarterPacksError$inboundSchema;
  /** @deprecated use `AppBskyGraphGetActorStarterPacksError$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphGetActorStarterPacksError$outboundSchema;
}

/** @internal */
export const AppBskyGraphGetActorStarterPacksResponseBody$inboundSchema:
  z.ZodType<
    AppBskyGraphGetActorStarterPacksResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: AppBskyGraphGetActorStarterPacksError$inboundSchema,
    message: z.string(),
  })
    .transform((v) => {
      return new AppBskyGraphGetActorStarterPacksResponseBody(v);
    });

/** @internal */
export type AppBskyGraphGetActorStarterPacksResponseBody$Outbound = {
  error: string;
  message: string;
};

/** @internal */
export const AppBskyGraphGetActorStarterPacksResponseBody$outboundSchema:
  z.ZodType<
    AppBskyGraphGetActorStarterPacksResponseBody$Outbound,
    z.ZodTypeDef,
    AppBskyGraphGetActorStarterPacksResponseBody
  > = z.instanceof(AppBskyGraphGetActorStarterPacksResponseBody)
    .transform(v => v.data$)
    .pipe(z.object({
      error: AppBskyGraphGetActorStarterPacksError$outboundSchema,
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphGetActorStarterPacksResponseBody$ {
  /** @deprecated use `AppBskyGraphGetActorStarterPacksResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyGraphGetActorStarterPacksResponseBody$inboundSchema;
  /** @deprecated use `AppBskyGraphGetActorStarterPacksResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphGetActorStarterPacksResponseBody$outboundSchema;
  /** @deprecated use `AppBskyGraphGetActorStarterPacksResponseBody$Outbound` instead. */
  export type Outbound = AppBskyGraphGetActorStarterPacksResponseBody$Outbound;
}
