/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";
import { BlueskyError } from "./blueskyerror.js";

/**
 * Unauthorized
 */
export type AppBskyGraphSearchStarterPacksAuthMissingErrorData = {
  error: "AuthMissing";
  message: string;
};

/**
 * Unauthorized
 */
export class AppBskyGraphSearchStarterPacksAuthMissingError
  extends BlueskyError
{
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: AppBskyGraphSearchStarterPacksAuthMissingErrorData;

  constructor(
    err: AppBskyGraphSearchStarterPacksAuthMissingErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "AppBskyGraphSearchStarterPacksAuthMissingError";
  }
}

export const AppBskyGraphSearchStarterPacksError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
} as const;
export type AppBskyGraphSearchStarterPacksError = ClosedEnum<
  typeof AppBskyGraphSearchStarterPacksError
>;

/**
 * Bad Request
 */
export type AppBskyGraphSearchStarterPacksBadRequestErrorData = {
  error: AppBskyGraphSearchStarterPacksError;
  message: string;
};

/**
 * Bad Request
 */
export class AppBskyGraphSearchStarterPacksBadRequestError
  extends BlueskyError
{
  error: AppBskyGraphSearchStarterPacksError;

  /** The original data that was passed to this error instance. */
  data$: AppBskyGraphSearchStarterPacksBadRequestErrorData;

  constructor(
    err: AppBskyGraphSearchStarterPacksBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "AppBskyGraphSearchStarterPacksBadRequestError";
  }
}

/** @internal */
export const AppBskyGraphSearchStarterPacksAuthMissingError$inboundSchema:
  z.ZodType<
    AppBskyGraphSearchStarterPacksAuthMissingError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.literal("AuthMissing").default("AuthMissing"),
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new AppBskyGraphSearchStarterPacksAuthMissingError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type AppBskyGraphSearchStarterPacksAuthMissingError$Outbound = {
  error: "AuthMissing";
  message: string;
};

/** @internal */
export const AppBskyGraphSearchStarterPacksAuthMissingError$outboundSchema:
  z.ZodType<
    AppBskyGraphSearchStarterPacksAuthMissingError$Outbound,
    z.ZodTypeDef,
    AppBskyGraphSearchStarterPacksAuthMissingError
  > = z.instanceof(AppBskyGraphSearchStarterPacksAuthMissingError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.literal("AuthMissing").default("AuthMissing" as const),
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphSearchStarterPacksAuthMissingError$ {
  /** @deprecated use `AppBskyGraphSearchStarterPacksAuthMissingError$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyGraphSearchStarterPacksAuthMissingError$inboundSchema;
  /** @deprecated use `AppBskyGraphSearchStarterPacksAuthMissingError$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphSearchStarterPacksAuthMissingError$outboundSchema;
  /** @deprecated use `AppBskyGraphSearchStarterPacksAuthMissingError$Outbound` instead. */
  export type Outbound =
    AppBskyGraphSearchStarterPacksAuthMissingError$Outbound;
}

/** @internal */
export const AppBskyGraphSearchStarterPacksError$inboundSchema: z.ZodNativeEnum<
  typeof AppBskyGraphSearchStarterPacksError
> = z.nativeEnum(AppBskyGraphSearchStarterPacksError);

/** @internal */
export const AppBskyGraphSearchStarterPacksError$outboundSchema:
  z.ZodNativeEnum<typeof AppBskyGraphSearchStarterPacksError> =
    AppBskyGraphSearchStarterPacksError$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphSearchStarterPacksError$ {
  /** @deprecated use `AppBskyGraphSearchStarterPacksError$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyGraphSearchStarterPacksError$inboundSchema;
  /** @deprecated use `AppBskyGraphSearchStarterPacksError$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphSearchStarterPacksError$outboundSchema;
}

/** @internal */
export const AppBskyGraphSearchStarterPacksBadRequestError$inboundSchema:
  z.ZodType<
    AppBskyGraphSearchStarterPacksBadRequestError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: AppBskyGraphSearchStarterPacksError$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new AppBskyGraphSearchStarterPacksBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type AppBskyGraphSearchStarterPacksBadRequestError$Outbound = {
  error: string;
  message: string;
};

/** @internal */
export const AppBskyGraphSearchStarterPacksBadRequestError$outboundSchema:
  z.ZodType<
    AppBskyGraphSearchStarterPacksBadRequestError$Outbound,
    z.ZodTypeDef,
    AppBskyGraphSearchStarterPacksBadRequestError
  > = z.instanceof(AppBskyGraphSearchStarterPacksBadRequestError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: AppBskyGraphSearchStarterPacksError$outboundSchema,
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphSearchStarterPacksBadRequestError$ {
  /** @deprecated use `AppBskyGraphSearchStarterPacksBadRequestError$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyGraphSearchStarterPacksBadRequestError$inboundSchema;
  /** @deprecated use `AppBskyGraphSearchStarterPacksBadRequestError$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphSearchStarterPacksBadRequestError$outboundSchema;
  /** @deprecated use `AppBskyGraphSearchStarterPacksBadRequestError$Outbound` instead. */
  export type Outbound = AppBskyGraphSearchStarterPacksBadRequestError$Outbound;
}
