/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Unauthorized
 */
export type UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyErrorData = {
  error: "AuthMissing";
  message: string;
};

/**
 * Unauthorized
 */
export class UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError
  extends Error
{
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyErrorData;

  constructor(
    err: UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyErrorData,
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError";
  }
}

export const AppBskyFeedGetFeedGeneratorsError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
} as const;
export type AppBskyFeedGetFeedGeneratorsError = ClosedEnum<
  typeof AppBskyFeedGetFeedGeneratorsError
>;

/**
 * Bad Request
 */
export type BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyErrorData = {
  error: AppBskyFeedGetFeedGeneratorsError;
  message: string;
};

/**
 * Bad Request
 */
export class BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError
  extends Error
{
  error: AppBskyFeedGetFeedGeneratorsError;

  /** The original data that was passed to this error instance. */
  data$: BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyErrorData;

  constructor(
    err: BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyErrorData,
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError";
  }
}

/** @internal */
export const UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError$inboundSchema:
  z.ZodType<
    UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.literal("AuthMissing"),
    message: z.string(),
  })
    .transform((v) => {
      return new UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError(v);
    });

/** @internal */
export type UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError$Outbound =
  {
    error: "AuthMissing";
    message: string;
  };

/** @internal */
export const UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError$outboundSchema:
  z.ZodType<
    UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError$Outbound,
    z.ZodTypeDef,
    UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError
  > = z.instanceof(UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.literal("AuthMissing").default("AuthMissing" as const),
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError$ {
  /** @deprecated use `UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError$inboundSchema` instead. */
  export const inboundSchema =
    UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError$inboundSchema;
  /** @deprecated use `UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError$outboundSchema` instead. */
  export const outboundSchema =
    UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError$outboundSchema;
  /** @deprecated use `UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError$Outbound` instead. */
  export type Outbound =
    UnauthorizedAppBskyFeedGetFeedGeneratorsResponseBodyError$Outbound;
}

/** @internal */
export const AppBskyFeedGetFeedGeneratorsError$inboundSchema: z.ZodNativeEnum<
  typeof AppBskyFeedGetFeedGeneratorsError
> = z.nativeEnum(AppBskyFeedGetFeedGeneratorsError);

/** @internal */
export const AppBskyFeedGetFeedGeneratorsError$outboundSchema: z.ZodNativeEnum<
  typeof AppBskyFeedGetFeedGeneratorsError
> = AppBskyFeedGetFeedGeneratorsError$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyFeedGetFeedGeneratorsError$ {
  /** @deprecated use `AppBskyFeedGetFeedGeneratorsError$inboundSchema` instead. */
  export const inboundSchema = AppBskyFeedGetFeedGeneratorsError$inboundSchema;
  /** @deprecated use `AppBskyFeedGetFeedGeneratorsError$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyFeedGetFeedGeneratorsError$outboundSchema;
}

/** @internal */
export const BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError$inboundSchema:
  z.ZodType<
    BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: AppBskyFeedGetFeedGeneratorsError$inboundSchema,
    message: z.string(),
  })
    .transform((v) => {
      return new BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError(v);
    });

/** @internal */
export type BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError$Outbound = {
  error: string;
  message: string;
};

/** @internal */
export const BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError$outboundSchema:
  z.ZodType<
    BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError$Outbound,
    z.ZodTypeDef,
    BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError
  > = z.instanceof(BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: AppBskyFeedGetFeedGeneratorsError$outboundSchema,
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError$ {
  /** @deprecated use `BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError$inboundSchema` instead. */
  export const inboundSchema =
    BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError$inboundSchema;
  /** @deprecated use `BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError$outboundSchema` instead. */
  export const outboundSchema =
    BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError$outboundSchema;
  /** @deprecated use `BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError$Outbound` instead. */
  export type Outbound =
    BadRequestAppBskyFeedGetFeedGeneratorsResponseBodyError$Outbound;
}
