/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";
import { BlueskyError } from "./blueskyerror.js";

/**
 * Unauthorized
 */
export type AppBskyGraphGetListsAuthMissingErrorData = {
  error: "AuthMissing";
  message: string;
};

/**
 * Unauthorized
 */
export class AppBskyGraphGetListsAuthMissingError extends BlueskyError {
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: AppBskyGraphGetListsAuthMissingErrorData;

  constructor(
    err: AppBskyGraphGetListsAuthMissingErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "AppBskyGraphGetListsAuthMissingError";
  }
}

export const AppBskyGraphGetListsError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
} as const;
export type AppBskyGraphGetListsError = ClosedEnum<
  typeof AppBskyGraphGetListsError
>;

/**
 * Bad Request
 */
export type AppBskyGraphGetListsBadRequestErrorData = {
  error: AppBskyGraphGetListsError;
  message: string;
};

/**
 * Bad Request
 */
export class AppBskyGraphGetListsBadRequestError extends BlueskyError {
  error: AppBskyGraphGetListsError;

  /** The original data that was passed to this error instance. */
  data$: AppBskyGraphGetListsBadRequestErrorData;

  constructor(
    err: AppBskyGraphGetListsBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "AppBskyGraphGetListsBadRequestError";
  }
}

/** @internal */
export const AppBskyGraphGetListsAuthMissingError$inboundSchema: z.ZodType<
  AppBskyGraphGetListsAuthMissingError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.literal("AuthMissing"),
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new AppBskyGraphGetListsAuthMissingError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type AppBskyGraphGetListsAuthMissingError$Outbound = {
  error: "AuthMissing";
  message: string;
};

/** @internal */
export const AppBskyGraphGetListsAuthMissingError$outboundSchema: z.ZodType<
  AppBskyGraphGetListsAuthMissingError$Outbound,
  z.ZodTypeDef,
  AppBskyGraphGetListsAuthMissingError
> = z.instanceof(AppBskyGraphGetListsAuthMissingError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.literal("AuthMissing"),
    message: z.string(),
  }));

/** @internal */
export const AppBskyGraphGetListsError$inboundSchema: z.ZodNativeEnum<
  typeof AppBskyGraphGetListsError
> = z.nativeEnum(AppBskyGraphGetListsError);
/** @internal */
export const AppBskyGraphGetListsError$outboundSchema: z.ZodNativeEnum<
  typeof AppBskyGraphGetListsError
> = AppBskyGraphGetListsError$inboundSchema;

/** @internal */
export const AppBskyGraphGetListsBadRequestError$inboundSchema: z.ZodType<
  AppBskyGraphGetListsBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: AppBskyGraphGetListsError$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new AppBskyGraphGetListsBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type AppBskyGraphGetListsBadRequestError$Outbound = {
  error: string;
  message: string;
};

/** @internal */
export const AppBskyGraphGetListsBadRequestError$outboundSchema: z.ZodType<
  AppBskyGraphGetListsBadRequestError$Outbound,
  z.ZodTypeDef,
  AppBskyGraphGetListsBadRequestError
> = z.instanceof(AppBskyGraphGetListsBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: AppBskyGraphGetListsError$outboundSchema,
    message: z.string(),
  }));
