/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Unauthorized
 */
export type AppBskyGraphMuteThreadAppBskyGraphResponseBodyData = {
  error: "AuthMissing";
  message: string;
};

/**
 * Unauthorized
 */
export class AppBskyGraphMuteThreadAppBskyGraphResponseBody extends Error {
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: AppBskyGraphMuteThreadAppBskyGraphResponseBodyData;

  constructor(err: AppBskyGraphMuteThreadAppBskyGraphResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "AppBskyGraphMuteThreadAppBskyGraphResponseBody";
  }
}

export const AppBskyGraphMuteThreadError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
} as const;
export type AppBskyGraphMuteThreadError = ClosedEnum<
  typeof AppBskyGraphMuteThreadError
>;

/**
 * Bad Request
 */
export type AppBskyGraphMuteThreadResponseBodyData = {
  error: AppBskyGraphMuteThreadError;
  message: string;
};

/**
 * Bad Request
 */
export class AppBskyGraphMuteThreadResponseBody extends Error {
  error: AppBskyGraphMuteThreadError;

  /** The original data that was passed to this error instance. */
  data$: AppBskyGraphMuteThreadResponseBodyData;

  constructor(err: AppBskyGraphMuteThreadResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "AppBskyGraphMuteThreadResponseBody";
  }
}

/** @internal */
export const AppBskyGraphMuteThreadAppBskyGraphResponseBody$inboundSchema:
  z.ZodType<
    AppBskyGraphMuteThreadAppBskyGraphResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.literal("AuthMissing"),
    message: z.string(),
  })
    .transform((v) => {
      return new AppBskyGraphMuteThreadAppBskyGraphResponseBody(v);
    });

/** @internal */
export type AppBskyGraphMuteThreadAppBskyGraphResponseBody$Outbound = {
  error: "AuthMissing";
  message: string;
};

/** @internal */
export const AppBskyGraphMuteThreadAppBskyGraphResponseBody$outboundSchema:
  z.ZodType<
    AppBskyGraphMuteThreadAppBskyGraphResponseBody$Outbound,
    z.ZodTypeDef,
    AppBskyGraphMuteThreadAppBskyGraphResponseBody
  > = z.instanceof(AppBskyGraphMuteThreadAppBskyGraphResponseBody)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.literal("AuthMissing").default("AuthMissing" as const),
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphMuteThreadAppBskyGraphResponseBody$ {
  /** @deprecated use `AppBskyGraphMuteThreadAppBskyGraphResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyGraphMuteThreadAppBskyGraphResponseBody$inboundSchema;
  /** @deprecated use `AppBskyGraphMuteThreadAppBskyGraphResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphMuteThreadAppBskyGraphResponseBody$outboundSchema;
  /** @deprecated use `AppBskyGraphMuteThreadAppBskyGraphResponseBody$Outbound` instead. */
  export type Outbound =
    AppBskyGraphMuteThreadAppBskyGraphResponseBody$Outbound;
}

/** @internal */
export const AppBskyGraphMuteThreadError$inboundSchema: z.ZodNativeEnum<
  typeof AppBskyGraphMuteThreadError
> = z.nativeEnum(AppBskyGraphMuteThreadError);

/** @internal */
export const AppBskyGraphMuteThreadError$outboundSchema: z.ZodNativeEnum<
  typeof AppBskyGraphMuteThreadError
> = AppBskyGraphMuteThreadError$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphMuteThreadError$ {
  /** @deprecated use `AppBskyGraphMuteThreadError$inboundSchema` instead. */
  export const inboundSchema = AppBskyGraphMuteThreadError$inboundSchema;
  /** @deprecated use `AppBskyGraphMuteThreadError$outboundSchema` instead. */
  export const outboundSchema = AppBskyGraphMuteThreadError$outboundSchema;
}

/** @internal */
export const AppBskyGraphMuteThreadResponseBody$inboundSchema: z.ZodType<
  AppBskyGraphMuteThreadResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: AppBskyGraphMuteThreadError$inboundSchema,
  message: z.string(),
})
  .transform((v) => {
    return new AppBskyGraphMuteThreadResponseBody(v);
  });

/** @internal */
export type AppBskyGraphMuteThreadResponseBody$Outbound = {
  error: string;
  message: string;
};

/** @internal */
export const AppBskyGraphMuteThreadResponseBody$outboundSchema: z.ZodType<
  AppBskyGraphMuteThreadResponseBody$Outbound,
  z.ZodTypeDef,
  AppBskyGraphMuteThreadResponseBody
> = z.instanceof(AppBskyGraphMuteThreadResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    error: AppBskyGraphMuteThreadError$outboundSchema,
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphMuteThreadResponseBody$ {
  /** @deprecated use `AppBskyGraphMuteThreadResponseBody$inboundSchema` instead. */
  export const inboundSchema = AppBskyGraphMuteThreadResponseBody$inboundSchema;
  /** @deprecated use `AppBskyGraphMuteThreadResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphMuteThreadResponseBody$outboundSchema;
  /** @deprecated use `AppBskyGraphMuteThreadResponseBody$Outbound` instead. */
  export type Outbound = AppBskyGraphMuteThreadResponseBody$Outbound;
}
