/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Unauthorized
 */
export type AppBskyLabelerGetServicesLabelersResponseBodyData = {
  error: "AuthMissing";
  message: string;
};

/**
 * Unauthorized
 */
export class AppBskyLabelerGetServicesLabelersResponseBody extends Error {
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: AppBskyLabelerGetServicesLabelersResponseBodyData;

  constructor(err: AppBskyLabelerGetServicesLabelersResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "AppBskyLabelerGetServicesLabelersResponseBody";
  }
}

export const AppBskyLabelerGetServicesError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
} as const;
export type AppBskyLabelerGetServicesError = ClosedEnum<
  typeof AppBskyLabelerGetServicesError
>;

/**
 * Bad Request
 */
export type AppBskyLabelerGetServicesResponseBodyData = {
  error: AppBskyLabelerGetServicesError;
  message: string;
};

/**
 * Bad Request
 */
export class AppBskyLabelerGetServicesResponseBody extends Error {
  error: AppBskyLabelerGetServicesError;

  /** The original data that was passed to this error instance. */
  data$: AppBskyLabelerGetServicesResponseBodyData;

  constructor(err: AppBskyLabelerGetServicesResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "AppBskyLabelerGetServicesResponseBody";
  }
}

/** @internal */
export const AppBskyLabelerGetServicesLabelersResponseBody$inboundSchema:
  z.ZodType<
    AppBskyLabelerGetServicesLabelersResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.literal("AuthMissing"),
    message: z.string(),
  })
    .transform((v) => {
      return new AppBskyLabelerGetServicesLabelersResponseBody(v);
    });

/** @internal */
export type AppBskyLabelerGetServicesLabelersResponseBody$Outbound = {
  error: "AuthMissing";
  message: string;
};

/** @internal */
export const AppBskyLabelerGetServicesLabelersResponseBody$outboundSchema:
  z.ZodType<
    AppBskyLabelerGetServicesLabelersResponseBody$Outbound,
    z.ZodTypeDef,
    AppBskyLabelerGetServicesLabelersResponseBody
  > = z.instanceof(AppBskyLabelerGetServicesLabelersResponseBody)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.literal("AuthMissing").default("AuthMissing" as const),
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyLabelerGetServicesLabelersResponseBody$ {
  /** @deprecated use `AppBskyLabelerGetServicesLabelersResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyLabelerGetServicesLabelersResponseBody$inboundSchema;
  /** @deprecated use `AppBskyLabelerGetServicesLabelersResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyLabelerGetServicesLabelersResponseBody$outboundSchema;
  /** @deprecated use `AppBskyLabelerGetServicesLabelersResponseBody$Outbound` instead. */
  export type Outbound = AppBskyLabelerGetServicesLabelersResponseBody$Outbound;
}

/** @internal */
export const AppBskyLabelerGetServicesError$inboundSchema: z.ZodNativeEnum<
  typeof AppBskyLabelerGetServicesError
> = z.nativeEnum(AppBskyLabelerGetServicesError);

/** @internal */
export const AppBskyLabelerGetServicesError$outboundSchema: z.ZodNativeEnum<
  typeof AppBskyLabelerGetServicesError
> = AppBskyLabelerGetServicesError$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyLabelerGetServicesError$ {
  /** @deprecated use `AppBskyLabelerGetServicesError$inboundSchema` instead. */
  export const inboundSchema = AppBskyLabelerGetServicesError$inboundSchema;
  /** @deprecated use `AppBskyLabelerGetServicesError$outboundSchema` instead. */
  export const outboundSchema = AppBskyLabelerGetServicesError$outboundSchema;
}

/** @internal */
export const AppBskyLabelerGetServicesResponseBody$inboundSchema: z.ZodType<
  AppBskyLabelerGetServicesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: AppBskyLabelerGetServicesError$inboundSchema,
  message: z.string(),
})
  .transform((v) => {
    return new AppBskyLabelerGetServicesResponseBody(v);
  });

/** @internal */
export type AppBskyLabelerGetServicesResponseBody$Outbound = {
  error: string;
  message: string;
};

/** @internal */
export const AppBskyLabelerGetServicesResponseBody$outboundSchema: z.ZodType<
  AppBskyLabelerGetServicesResponseBody$Outbound,
  z.ZodTypeDef,
  AppBskyLabelerGetServicesResponseBody
> = z.instanceof(AppBskyLabelerGetServicesResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    error: AppBskyLabelerGetServicesError$outboundSchema,
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyLabelerGetServicesResponseBody$ {
  /** @deprecated use `AppBskyLabelerGetServicesResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyLabelerGetServicesResponseBody$inboundSchema;
  /** @deprecated use `AppBskyLabelerGetServicesResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyLabelerGetServicesResponseBody$outboundSchema;
  /** @deprecated use `AppBskyLabelerGetServicesResponseBody$Outbound` instead. */
  export type Outbound = AppBskyLabelerGetServicesResponseBody$Outbound;
}
