/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";
import { BlueskyError } from "./blueskyerror.js";

/**
 * Unauthorized
 */
export type AppBskyGraphGetKnownFollowersAuthMissingErrorData = {
  error: "AuthMissing";
  message: string;
};

/**
 * Unauthorized
 */
export class AppBskyGraphGetKnownFollowersAuthMissingError
  extends BlueskyError
{
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: AppBskyGraphGetKnownFollowersAuthMissingErrorData;

  constructor(
    err: AppBskyGraphGetKnownFollowersAuthMissingErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "AppBskyGraphGetKnownFollowersAuthMissingError";
  }
}

export const AppBskyGraphGetKnownFollowersError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
} as const;
export type AppBskyGraphGetKnownFollowersError = ClosedEnum<
  typeof AppBskyGraphGetKnownFollowersError
>;

/**
 * Bad Request
 */
export type AppBskyGraphGetKnownFollowersBadRequestErrorData = {
  error: AppBskyGraphGetKnownFollowersError;
  message: string;
};

/**
 * Bad Request
 */
export class AppBskyGraphGetKnownFollowersBadRequestError extends BlueskyError {
  error: AppBskyGraphGetKnownFollowersError;

  /** The original data that was passed to this error instance. */
  data$: AppBskyGraphGetKnownFollowersBadRequestErrorData;

  constructor(
    err: AppBskyGraphGetKnownFollowersBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "AppBskyGraphGetKnownFollowersBadRequestError";
  }
}

/** @internal */
export const AppBskyGraphGetKnownFollowersAuthMissingError$inboundSchema:
  z.ZodType<
    AppBskyGraphGetKnownFollowersAuthMissingError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.literal("AuthMissing").default("AuthMissing"),
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new AppBskyGraphGetKnownFollowersAuthMissingError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type AppBskyGraphGetKnownFollowersAuthMissingError$Outbound = {
  error: "AuthMissing";
  message: string;
};

/** @internal */
export const AppBskyGraphGetKnownFollowersAuthMissingError$outboundSchema:
  z.ZodType<
    AppBskyGraphGetKnownFollowersAuthMissingError$Outbound,
    z.ZodTypeDef,
    AppBskyGraphGetKnownFollowersAuthMissingError
  > = z.instanceof(AppBskyGraphGetKnownFollowersAuthMissingError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.literal("AuthMissing").default("AuthMissing" as const),
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphGetKnownFollowersAuthMissingError$ {
  /** @deprecated use `AppBskyGraphGetKnownFollowersAuthMissingError$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyGraphGetKnownFollowersAuthMissingError$inboundSchema;
  /** @deprecated use `AppBskyGraphGetKnownFollowersAuthMissingError$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphGetKnownFollowersAuthMissingError$outboundSchema;
  /** @deprecated use `AppBskyGraphGetKnownFollowersAuthMissingError$Outbound` instead. */
  export type Outbound = AppBskyGraphGetKnownFollowersAuthMissingError$Outbound;
}

/** @internal */
export const AppBskyGraphGetKnownFollowersError$inboundSchema: z.ZodNativeEnum<
  typeof AppBskyGraphGetKnownFollowersError
> = z.nativeEnum(AppBskyGraphGetKnownFollowersError);

/** @internal */
export const AppBskyGraphGetKnownFollowersError$outboundSchema: z.ZodNativeEnum<
  typeof AppBskyGraphGetKnownFollowersError
> = AppBskyGraphGetKnownFollowersError$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphGetKnownFollowersError$ {
  /** @deprecated use `AppBskyGraphGetKnownFollowersError$inboundSchema` instead. */
  export const inboundSchema = AppBskyGraphGetKnownFollowersError$inboundSchema;
  /** @deprecated use `AppBskyGraphGetKnownFollowersError$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphGetKnownFollowersError$outboundSchema;
}

/** @internal */
export const AppBskyGraphGetKnownFollowersBadRequestError$inboundSchema:
  z.ZodType<
    AppBskyGraphGetKnownFollowersBadRequestError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: AppBskyGraphGetKnownFollowersError$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new AppBskyGraphGetKnownFollowersBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type AppBskyGraphGetKnownFollowersBadRequestError$Outbound = {
  error: string;
  message: string;
};

/** @internal */
export const AppBskyGraphGetKnownFollowersBadRequestError$outboundSchema:
  z.ZodType<
    AppBskyGraphGetKnownFollowersBadRequestError$Outbound,
    z.ZodTypeDef,
    AppBskyGraphGetKnownFollowersBadRequestError
  > = z.instanceof(AppBskyGraphGetKnownFollowersBadRequestError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: AppBskyGraphGetKnownFollowersError$outboundSchema,
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphGetKnownFollowersBadRequestError$ {
  /** @deprecated use `AppBskyGraphGetKnownFollowersBadRequestError$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyGraphGetKnownFollowersBadRequestError$inboundSchema;
  /** @deprecated use `AppBskyGraphGetKnownFollowersBadRequestError$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphGetKnownFollowersBadRequestError$outboundSchema;
  /** @deprecated use `AppBskyGraphGetKnownFollowersBadRequestError$Outbound` instead. */
  export type Outbound = AppBskyGraphGetKnownFollowersBadRequestError$Outbound;
}
