/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Unauthorized
 */
export type AppBskyGraphGetListsAppBskyGraphResponseBodyData = {
  error: "AuthMissing";
  message: string;
};

/**
 * Unauthorized
 */
export class AppBskyGraphGetListsAppBskyGraphResponseBody extends Error {
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: AppBskyGraphGetListsAppBskyGraphResponseBodyData;

  constructor(err: AppBskyGraphGetListsAppBskyGraphResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "AppBskyGraphGetListsAppBskyGraphResponseBody";
  }
}

export const AppBskyGraphGetListsError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
} as const;
export type AppBskyGraphGetListsError = ClosedEnum<
  typeof AppBskyGraphGetListsError
>;

/**
 * Bad Request
 */
export type AppBskyGraphGetListsResponseBodyData = {
  error: AppBskyGraphGetListsError;
  message: string;
};

/**
 * Bad Request
 */
export class AppBskyGraphGetListsResponseBody extends Error {
  error: AppBskyGraphGetListsError;

  /** The original data that was passed to this error instance. */
  data$: AppBskyGraphGetListsResponseBodyData;

  constructor(err: AppBskyGraphGetListsResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "AppBskyGraphGetListsResponseBody";
  }
}

/** @internal */
export const AppBskyGraphGetListsAppBskyGraphResponseBody$inboundSchema:
  z.ZodType<
    AppBskyGraphGetListsAppBskyGraphResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.literal("AuthMissing"),
    message: z.string(),
  })
    .transform((v) => {
      return new AppBskyGraphGetListsAppBskyGraphResponseBody(v);
    });

/** @internal */
export type AppBskyGraphGetListsAppBskyGraphResponseBody$Outbound = {
  error: "AuthMissing";
  message: string;
};

/** @internal */
export const AppBskyGraphGetListsAppBskyGraphResponseBody$outboundSchema:
  z.ZodType<
    AppBskyGraphGetListsAppBskyGraphResponseBody$Outbound,
    z.ZodTypeDef,
    AppBskyGraphGetListsAppBskyGraphResponseBody
  > = z.instanceof(AppBskyGraphGetListsAppBskyGraphResponseBody)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.literal("AuthMissing").default("AuthMissing" as const),
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphGetListsAppBskyGraphResponseBody$ {
  /** @deprecated use `AppBskyGraphGetListsAppBskyGraphResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyGraphGetListsAppBskyGraphResponseBody$inboundSchema;
  /** @deprecated use `AppBskyGraphGetListsAppBskyGraphResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphGetListsAppBskyGraphResponseBody$outboundSchema;
  /** @deprecated use `AppBskyGraphGetListsAppBskyGraphResponseBody$Outbound` instead. */
  export type Outbound = AppBskyGraphGetListsAppBskyGraphResponseBody$Outbound;
}

/** @internal */
export const AppBskyGraphGetListsError$inboundSchema: z.ZodNativeEnum<
  typeof AppBskyGraphGetListsError
> = z.nativeEnum(AppBskyGraphGetListsError);

/** @internal */
export const AppBskyGraphGetListsError$outboundSchema: z.ZodNativeEnum<
  typeof AppBskyGraphGetListsError
> = AppBskyGraphGetListsError$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphGetListsError$ {
  /** @deprecated use `AppBskyGraphGetListsError$inboundSchema` instead. */
  export const inboundSchema = AppBskyGraphGetListsError$inboundSchema;
  /** @deprecated use `AppBskyGraphGetListsError$outboundSchema` instead. */
  export const outboundSchema = AppBskyGraphGetListsError$outboundSchema;
}

/** @internal */
export const AppBskyGraphGetListsResponseBody$inboundSchema: z.ZodType<
  AppBskyGraphGetListsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: AppBskyGraphGetListsError$inboundSchema,
  message: z.string(),
})
  .transform((v) => {
    return new AppBskyGraphGetListsResponseBody(v);
  });

/** @internal */
export type AppBskyGraphGetListsResponseBody$Outbound = {
  error: string;
  message: string;
};

/** @internal */
export const AppBskyGraphGetListsResponseBody$outboundSchema: z.ZodType<
  AppBskyGraphGetListsResponseBody$Outbound,
  z.ZodTypeDef,
  AppBskyGraphGetListsResponseBody
> = z.instanceof(AppBskyGraphGetListsResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    error: AppBskyGraphGetListsError$outboundSchema,
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphGetListsResponseBody$ {
  /** @deprecated use `AppBskyGraphGetListsResponseBody$inboundSchema` instead. */
  export const inboundSchema = AppBskyGraphGetListsResponseBody$inboundSchema;
  /** @deprecated use `AppBskyGraphGetListsResponseBody$outboundSchema` instead. */
  export const outboundSchema = AppBskyGraphGetListsResponseBody$outboundSchema;
  /** @deprecated use `AppBskyGraphGetListsResponseBody$Outbound` instead. */
  export type Outbound = AppBskyGraphGetListsResponseBody$Outbound;
}
