/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";
import { BlueskyError } from "./blueskyerror.js";

/**
 * Unauthorized
 */
export type AppBskyGraphGetActorStarterPacksAuthMissingErrorData = {
  error: "AuthMissing";
  message: string;
};

/**
 * Unauthorized
 */
export class AppBskyGraphGetActorStarterPacksAuthMissingError
  extends BlueskyError
{
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: AppBskyGraphGetActorStarterPacksAuthMissingErrorData;

  constructor(
    err: AppBskyGraphGetActorStarterPacksAuthMissingErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "AppBskyGraphGetActorStarterPacksAuthMissingError";
  }
}

export const AppBskyGraphGetActorStarterPacksError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
} as const;
export type AppBskyGraphGetActorStarterPacksError = ClosedEnum<
  typeof AppBskyGraphGetActorStarterPacksError
>;

/**
 * Bad Request
 */
export type AppBskyGraphGetActorStarterPacksBadRequestErrorData = {
  error: AppBskyGraphGetActorStarterPacksError;
  message: string;
};

/**
 * Bad Request
 */
export class AppBskyGraphGetActorStarterPacksBadRequestError
  extends BlueskyError
{
  error: AppBskyGraphGetActorStarterPacksError;

  /** The original data that was passed to this error instance. */
  data$: AppBskyGraphGetActorStarterPacksBadRequestErrorData;

  constructor(
    err: AppBskyGraphGetActorStarterPacksBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "AppBskyGraphGetActorStarterPacksBadRequestError";
  }
}

/** @internal */
export const AppBskyGraphGetActorStarterPacksAuthMissingError$inboundSchema:
  z.ZodType<
    AppBskyGraphGetActorStarterPacksAuthMissingError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.literal("AuthMissing").default("AuthMissing"),
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new AppBskyGraphGetActorStarterPacksAuthMissingError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type AppBskyGraphGetActorStarterPacksAuthMissingError$Outbound = {
  error: "AuthMissing";
  message: string;
};

/** @internal */
export const AppBskyGraphGetActorStarterPacksAuthMissingError$outboundSchema:
  z.ZodType<
    AppBskyGraphGetActorStarterPacksAuthMissingError$Outbound,
    z.ZodTypeDef,
    AppBskyGraphGetActorStarterPacksAuthMissingError
  > = z.instanceof(AppBskyGraphGetActorStarterPacksAuthMissingError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.literal("AuthMissing").default("AuthMissing" as const),
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphGetActorStarterPacksAuthMissingError$ {
  /** @deprecated use `AppBskyGraphGetActorStarterPacksAuthMissingError$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyGraphGetActorStarterPacksAuthMissingError$inboundSchema;
  /** @deprecated use `AppBskyGraphGetActorStarterPacksAuthMissingError$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphGetActorStarterPacksAuthMissingError$outboundSchema;
  /** @deprecated use `AppBskyGraphGetActorStarterPacksAuthMissingError$Outbound` instead. */
  export type Outbound =
    AppBskyGraphGetActorStarterPacksAuthMissingError$Outbound;
}

/** @internal */
export const AppBskyGraphGetActorStarterPacksError$inboundSchema:
  z.ZodNativeEnum<typeof AppBskyGraphGetActorStarterPacksError> = z.nativeEnum(
    AppBskyGraphGetActorStarterPacksError,
  );

/** @internal */
export const AppBskyGraphGetActorStarterPacksError$outboundSchema:
  z.ZodNativeEnum<typeof AppBskyGraphGetActorStarterPacksError> =
    AppBskyGraphGetActorStarterPacksError$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphGetActorStarterPacksError$ {
  /** @deprecated use `AppBskyGraphGetActorStarterPacksError$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyGraphGetActorStarterPacksError$inboundSchema;
  /** @deprecated use `AppBskyGraphGetActorStarterPacksError$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphGetActorStarterPacksError$outboundSchema;
}

/** @internal */
export const AppBskyGraphGetActorStarterPacksBadRequestError$inboundSchema:
  z.ZodType<
    AppBskyGraphGetActorStarterPacksBadRequestError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: AppBskyGraphGetActorStarterPacksError$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new AppBskyGraphGetActorStarterPacksBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type AppBskyGraphGetActorStarterPacksBadRequestError$Outbound = {
  error: string;
  message: string;
};

/** @internal */
export const AppBskyGraphGetActorStarterPacksBadRequestError$outboundSchema:
  z.ZodType<
    AppBskyGraphGetActorStarterPacksBadRequestError$Outbound,
    z.ZodTypeDef,
    AppBskyGraphGetActorStarterPacksBadRequestError
  > = z.instanceof(AppBskyGraphGetActorStarterPacksBadRequestError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: AppBskyGraphGetActorStarterPacksError$outboundSchema,
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphGetActorStarterPacksBadRequestError$ {
  /** @deprecated use `AppBskyGraphGetActorStarterPacksBadRequestError$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyGraphGetActorStarterPacksBadRequestError$inboundSchema;
  /** @deprecated use `AppBskyGraphGetActorStarterPacksBadRequestError$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphGetActorStarterPacksBadRequestError$outboundSchema;
  /** @deprecated use `AppBskyGraphGetActorStarterPacksBadRequestError$Outbound` instead. */
  export type Outbound =
    AppBskyGraphGetActorStarterPacksBadRequestError$Outbound;
}
