/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";
import { BlueskyError } from "./blueskyerror.js";

/**
 * Unauthorized
 */
export type ChatBskyModerationGetActorMetadataAuthMissingErrorData = {
  error: "AuthMissing";
  message: string;
};

/**
 * Unauthorized
 */
export class ChatBskyModerationGetActorMetadataAuthMissingError
  extends BlueskyError
{
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: ChatBskyModerationGetActorMetadataAuthMissingErrorData;

  constructor(
    err: ChatBskyModerationGetActorMetadataAuthMissingErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ChatBskyModerationGetActorMetadataAuthMissingError";
  }
}

export const ChatBskyModerationGetActorMetadataError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
} as const;
export type ChatBskyModerationGetActorMetadataError = ClosedEnum<
  typeof ChatBskyModerationGetActorMetadataError
>;

/**
 * Bad Request
 */
export type ChatBskyModerationGetActorMetadataBadRequestErrorData = {
  error: ChatBskyModerationGetActorMetadataError;
  message: string;
};

/**
 * Bad Request
 */
export class ChatBskyModerationGetActorMetadataBadRequestError
  extends BlueskyError
{
  error: ChatBskyModerationGetActorMetadataError;

  /** The original data that was passed to this error instance. */
  data$: ChatBskyModerationGetActorMetadataBadRequestErrorData;

  constructor(
    err: ChatBskyModerationGetActorMetadataBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ChatBskyModerationGetActorMetadataBadRequestError";
  }
}

/** @internal */
export const ChatBskyModerationGetActorMetadataAuthMissingError$inboundSchema:
  z.ZodType<
    ChatBskyModerationGetActorMetadataAuthMissingError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.literal("AuthMissing"),
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new ChatBskyModerationGetActorMetadataAuthMissingError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type ChatBskyModerationGetActorMetadataAuthMissingError$Outbound = {
  error: "AuthMissing";
  message: string;
};

/** @internal */
export const ChatBskyModerationGetActorMetadataAuthMissingError$outboundSchema:
  z.ZodType<
    ChatBskyModerationGetActorMetadataAuthMissingError$Outbound,
    z.ZodTypeDef,
    ChatBskyModerationGetActorMetadataAuthMissingError
  > = z.instanceof(ChatBskyModerationGetActorMetadataAuthMissingError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.literal("AuthMissing"),
      message: z.string(),
    }));

/** @internal */
export const ChatBskyModerationGetActorMetadataError$inboundSchema:
  z.ZodNativeEnum<typeof ChatBskyModerationGetActorMetadataError> = z
    .nativeEnum(ChatBskyModerationGetActorMetadataError);
/** @internal */
export const ChatBskyModerationGetActorMetadataError$outboundSchema:
  z.ZodNativeEnum<typeof ChatBskyModerationGetActorMetadataError> =
    ChatBskyModerationGetActorMetadataError$inboundSchema;

/** @internal */
export const ChatBskyModerationGetActorMetadataBadRequestError$inboundSchema:
  z.ZodType<
    ChatBskyModerationGetActorMetadataBadRequestError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: ChatBskyModerationGetActorMetadataError$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new ChatBskyModerationGetActorMetadataBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type ChatBskyModerationGetActorMetadataBadRequestError$Outbound = {
  error: string;
  message: string;
};

/** @internal */
export const ChatBskyModerationGetActorMetadataBadRequestError$outboundSchema:
  z.ZodType<
    ChatBskyModerationGetActorMetadataBadRequestError$Outbound,
    z.ZodTypeDef,
    ChatBskyModerationGetActorMetadataBadRequestError
  > = z.instanceof(ChatBskyModerationGetActorMetadataBadRequestError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: ChatBskyModerationGetActorMetadataError$outboundSchema,
      message: z.string(),
    }));
