/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Unauthorized
 */
export type UnauthorizedChatBskyModerationGetActorMetadataResponseBodyErrorData =
  {
    error: "AuthMissing";
    message: string;
  };

/**
 * Unauthorized
 */
export class UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError
  extends Error
{
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: UnauthorizedChatBskyModerationGetActorMetadataResponseBodyErrorData;

  constructor(
    err: UnauthorizedChatBskyModerationGetActorMetadataResponseBodyErrorData,
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name =
      "UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError";
  }
}

export const ChatBskyModerationGetActorMetadataError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
} as const;
export type ChatBskyModerationGetActorMetadataError = ClosedEnum<
  typeof ChatBskyModerationGetActorMetadataError
>;

/**
 * Bad Request
 */
export type BadRequestChatBskyModerationGetActorMetadataResponseBodyErrorData =
  {
    error: ChatBskyModerationGetActorMetadataError;
    message: string;
  };

/**
 * Bad Request
 */
export class BadRequestChatBskyModerationGetActorMetadataResponseBodyError
  extends Error
{
  error: ChatBskyModerationGetActorMetadataError;

  /** The original data that was passed to this error instance. */
  data$: BadRequestChatBskyModerationGetActorMetadataResponseBodyErrorData;

  constructor(
    err: BadRequestChatBskyModerationGetActorMetadataResponseBodyErrorData,
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "BadRequestChatBskyModerationGetActorMetadataResponseBodyError";
  }
}

/** @internal */
export const UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError$inboundSchema:
  z.ZodType<
    UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.literal("AuthMissing"),
    message: z.string(),
  })
    .transform((v) => {
      return new UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError(
        v,
      );
    });

/** @internal */
export type UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError$Outbound =
  {
    error: "AuthMissing";
    message: string;
  };

/** @internal */
export const UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError$outboundSchema:
  z.ZodType<
    UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError$Outbound,
    z.ZodTypeDef,
    UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError
  > = z.instanceof(
    UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.literal("AuthMissing").default("AuthMissing" as const),
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError$ {
  /** @deprecated use `UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError$inboundSchema` instead. */
  export const inboundSchema =
    UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError$inboundSchema;
  /** @deprecated use `UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError$outboundSchema` instead. */
  export const outboundSchema =
    UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError$outboundSchema;
  /** @deprecated use `UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError$Outbound` instead. */
  export type Outbound =
    UnauthorizedChatBskyModerationGetActorMetadataResponseBodyError$Outbound;
}

/** @internal */
export const ChatBskyModerationGetActorMetadataError$inboundSchema:
  z.ZodNativeEnum<typeof ChatBskyModerationGetActorMetadataError> = z
    .nativeEnum(ChatBskyModerationGetActorMetadataError);

/** @internal */
export const ChatBskyModerationGetActorMetadataError$outboundSchema:
  z.ZodNativeEnum<typeof ChatBskyModerationGetActorMetadataError> =
    ChatBskyModerationGetActorMetadataError$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatBskyModerationGetActorMetadataError$ {
  /** @deprecated use `ChatBskyModerationGetActorMetadataError$inboundSchema` instead. */
  export const inboundSchema =
    ChatBskyModerationGetActorMetadataError$inboundSchema;
  /** @deprecated use `ChatBskyModerationGetActorMetadataError$outboundSchema` instead. */
  export const outboundSchema =
    ChatBskyModerationGetActorMetadataError$outboundSchema;
}

/** @internal */
export const BadRequestChatBskyModerationGetActorMetadataResponseBodyError$inboundSchema:
  z.ZodType<
    BadRequestChatBskyModerationGetActorMetadataResponseBodyError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: ChatBskyModerationGetActorMetadataError$inboundSchema,
    message: z.string(),
  })
    .transform((v) => {
      return new BadRequestChatBskyModerationGetActorMetadataResponseBodyError(
        v,
      );
    });

/** @internal */
export type BadRequestChatBskyModerationGetActorMetadataResponseBodyError$Outbound =
  {
    error: string;
    message: string;
  };

/** @internal */
export const BadRequestChatBskyModerationGetActorMetadataResponseBodyError$outboundSchema:
  z.ZodType<
    BadRequestChatBskyModerationGetActorMetadataResponseBodyError$Outbound,
    z.ZodTypeDef,
    BadRequestChatBskyModerationGetActorMetadataResponseBodyError
  > = z.instanceof(
    BadRequestChatBskyModerationGetActorMetadataResponseBodyError,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      error: ChatBskyModerationGetActorMetadataError$outboundSchema,
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BadRequestChatBskyModerationGetActorMetadataResponseBodyError$ {
  /** @deprecated use `BadRequestChatBskyModerationGetActorMetadataResponseBodyError$inboundSchema` instead. */
  export const inboundSchema =
    BadRequestChatBskyModerationGetActorMetadataResponseBodyError$inboundSchema;
  /** @deprecated use `BadRequestChatBskyModerationGetActorMetadataResponseBodyError$outboundSchema` instead. */
  export const outboundSchema =
    BadRequestChatBskyModerationGetActorMetadataResponseBodyError$outboundSchema;
  /** @deprecated use `BadRequestChatBskyModerationGetActorMetadataResponseBodyError$Outbound` instead. */
  export type Outbound =
    BadRequestChatBskyModerationGetActorMetadataResponseBodyError$Outbound;
}
