/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Unauthorized
 */
export type ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBodyData = {
  error: "AuthMissing";
  message: string;
};

/**
 * Unauthorized
 */
export class ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody
  extends Error
{
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBodyData;

  constructor(err: ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody";
  }
}

export const ComAtprotoAdminGetInviteCodesError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
} as const;
export type ComAtprotoAdminGetInviteCodesError = ClosedEnum<
  typeof ComAtprotoAdminGetInviteCodesError
>;

/**
 * Bad Request
 */
export type ComAtprotoAdminGetInviteCodesResponseBodyData = {
  error: ComAtprotoAdminGetInviteCodesError;
  message: string;
};

/**
 * Bad Request
 */
export class ComAtprotoAdminGetInviteCodesResponseBody extends Error {
  error: ComAtprotoAdminGetInviteCodesError;

  /** The original data that was passed to this error instance. */
  data$: ComAtprotoAdminGetInviteCodesResponseBodyData;

  constructor(err: ComAtprotoAdminGetInviteCodesResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "ComAtprotoAdminGetInviteCodesResponseBody";
  }
}

/** @internal */
export const ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody$inboundSchema:
  z.ZodType<
    ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.literal("AuthMissing"),
    message: z.string(),
  })
    .transform((v) => {
      return new ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody(v);
    });

/** @internal */
export type ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody$Outbound = {
  error: "AuthMissing";
  message: string;
};

/** @internal */
export const ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody$outboundSchema:
  z.ZodType<
    ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody$Outbound,
    z.ZodTypeDef,
    ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody
  > = z.instanceof(ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.literal("AuthMissing").default("AuthMissing" as const),
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody$ {
  /** @deprecated use `ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody$inboundSchema;
  /** @deprecated use `ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody$outboundSchema;
  /** @deprecated use `ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody$Outbound` instead. */
  export type Outbound =
    ComAtprotoAdminGetInviteCodesAtprotoAdminResponseBody$Outbound;
}

/** @internal */
export const ComAtprotoAdminGetInviteCodesError$inboundSchema: z.ZodNativeEnum<
  typeof ComAtprotoAdminGetInviteCodesError
> = z.nativeEnum(ComAtprotoAdminGetInviteCodesError);

/** @internal */
export const ComAtprotoAdminGetInviteCodesError$outboundSchema: z.ZodNativeEnum<
  typeof ComAtprotoAdminGetInviteCodesError
> = ComAtprotoAdminGetInviteCodesError$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComAtprotoAdminGetInviteCodesError$ {
  /** @deprecated use `ComAtprotoAdminGetInviteCodesError$inboundSchema` instead. */
  export const inboundSchema = ComAtprotoAdminGetInviteCodesError$inboundSchema;
  /** @deprecated use `ComAtprotoAdminGetInviteCodesError$outboundSchema` instead. */
  export const outboundSchema =
    ComAtprotoAdminGetInviteCodesError$outboundSchema;
}

/** @internal */
export const ComAtprotoAdminGetInviteCodesResponseBody$inboundSchema: z.ZodType<
  ComAtprotoAdminGetInviteCodesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: ComAtprotoAdminGetInviteCodesError$inboundSchema,
  message: z.string(),
})
  .transform((v) => {
    return new ComAtprotoAdminGetInviteCodesResponseBody(v);
  });

/** @internal */
export type ComAtprotoAdminGetInviteCodesResponseBody$Outbound = {
  error: string;
  message: string;
};

/** @internal */
export const ComAtprotoAdminGetInviteCodesResponseBody$outboundSchema:
  z.ZodType<
    ComAtprotoAdminGetInviteCodesResponseBody$Outbound,
    z.ZodTypeDef,
    ComAtprotoAdminGetInviteCodesResponseBody
  > = z.instanceof(ComAtprotoAdminGetInviteCodesResponseBody)
    .transform(v => v.data$)
    .pipe(z.object({
      error: ComAtprotoAdminGetInviteCodesError$outboundSchema,
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComAtprotoAdminGetInviteCodesResponseBody$ {
  /** @deprecated use `ComAtprotoAdminGetInviteCodesResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    ComAtprotoAdminGetInviteCodesResponseBody$inboundSchema;
  /** @deprecated use `ComAtprotoAdminGetInviteCodesResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    ComAtprotoAdminGetInviteCodesResponseBody$outboundSchema;
  /** @deprecated use `ComAtprotoAdminGetInviteCodesResponseBody$Outbound` instead. */
  export type Outbound = ComAtprotoAdminGetInviteCodesResponseBody$Outbound;
}
