/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";
import { BlueskyError } from "./blueskyerror.js";

/**
 * Unauthorized
 */
export type ComAtprotoServerCheckAccountStatusAuthMissingErrorData = {
  error: "AuthMissing";
  message: string;
};

/**
 * Unauthorized
 */
export class ComAtprotoServerCheckAccountStatusAuthMissingError
  extends BlueskyError
{
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: ComAtprotoServerCheckAccountStatusAuthMissingErrorData;

  constructor(
    err: ComAtprotoServerCheckAccountStatusAuthMissingErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ComAtprotoServerCheckAccountStatusAuthMissingError";
  }
}

export const ComAtprotoServerCheckAccountStatusError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
} as const;
export type ComAtprotoServerCheckAccountStatusError = ClosedEnum<
  typeof ComAtprotoServerCheckAccountStatusError
>;

/**
 * Bad Request
 */
export type ComAtprotoServerCheckAccountStatusBadRequestErrorData = {
  error: ComAtprotoServerCheckAccountStatusError;
  message: string;
};

/**
 * Bad Request
 */
export class ComAtprotoServerCheckAccountStatusBadRequestError
  extends BlueskyError
{
  error: ComAtprotoServerCheckAccountStatusError;

  /** The original data that was passed to this error instance. */
  data$: ComAtprotoServerCheckAccountStatusBadRequestErrorData;

  constructor(
    err: ComAtprotoServerCheckAccountStatusBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ComAtprotoServerCheckAccountStatusBadRequestError";
  }
}

/** @internal */
export const ComAtprotoServerCheckAccountStatusAuthMissingError$inboundSchema:
  z.ZodType<
    ComAtprotoServerCheckAccountStatusAuthMissingError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.literal("AuthMissing"),
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new ComAtprotoServerCheckAccountStatusAuthMissingError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type ComAtprotoServerCheckAccountStatusAuthMissingError$Outbound = {
  error: "AuthMissing";
  message: string;
};

/** @internal */
export const ComAtprotoServerCheckAccountStatusAuthMissingError$outboundSchema:
  z.ZodType<
    ComAtprotoServerCheckAccountStatusAuthMissingError$Outbound,
    z.ZodTypeDef,
    ComAtprotoServerCheckAccountStatusAuthMissingError
  > = z.instanceof(ComAtprotoServerCheckAccountStatusAuthMissingError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.literal("AuthMissing"),
      message: z.string(),
    }));

/** @internal */
export const ComAtprotoServerCheckAccountStatusError$inboundSchema:
  z.ZodNativeEnum<typeof ComAtprotoServerCheckAccountStatusError> = z
    .nativeEnum(ComAtprotoServerCheckAccountStatusError);
/** @internal */
export const ComAtprotoServerCheckAccountStatusError$outboundSchema:
  z.ZodNativeEnum<typeof ComAtprotoServerCheckAccountStatusError> =
    ComAtprotoServerCheckAccountStatusError$inboundSchema;

/** @internal */
export const ComAtprotoServerCheckAccountStatusBadRequestError$inboundSchema:
  z.ZodType<
    ComAtprotoServerCheckAccountStatusBadRequestError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: ComAtprotoServerCheckAccountStatusError$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new ComAtprotoServerCheckAccountStatusBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type ComAtprotoServerCheckAccountStatusBadRequestError$Outbound = {
  error: string;
  message: string;
};

/** @internal */
export const ComAtprotoServerCheckAccountStatusBadRequestError$outboundSchema:
  z.ZodType<
    ComAtprotoServerCheckAccountStatusBadRequestError$Outbound,
    z.ZodTypeDef,
    ComAtprotoServerCheckAccountStatusBadRequestError
  > = z.instanceof(ComAtprotoServerCheckAccountStatusBadRequestError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: ComAtprotoServerCheckAccountStatusError$outboundSchema,
      message: z.string(),
    }));
