/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";
import { BlueskyError } from "./blueskyerror.js";

/**
 * Unauthorized
 */
export type ComAtprotoSyncGetBlobAuthMissingErrorData = {
  error: "AuthMissing";
  message: string;
};

/**
 * Unauthorized
 */
export class ComAtprotoSyncGetBlobAuthMissingError extends BlueskyError {
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: ComAtprotoSyncGetBlobAuthMissingErrorData;

  constructor(
    err: ComAtprotoSyncGetBlobAuthMissingErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ComAtprotoSyncGetBlobAuthMissingError";
  }
}

export const ComAtprotoSyncGetBlobError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
  BlobNotFound: "BlobNotFound",
  RepoNotFound: "RepoNotFound",
  RepoTakendown: "RepoTakendown",
  RepoSuspended: "RepoSuspended",
  RepoDeactivated: "RepoDeactivated",
} as const;
export type ComAtprotoSyncGetBlobError = ClosedEnum<
  typeof ComAtprotoSyncGetBlobError
>;

/**
 * Bad Request
 */
export type ComAtprotoSyncGetBlobBadRequestErrorData = {
  error: ComAtprotoSyncGetBlobError;
  message: string;
};

/**
 * Bad Request
 */
export class ComAtprotoSyncGetBlobBadRequestError extends BlueskyError {
  error: ComAtprotoSyncGetBlobError;

  /** The original data that was passed to this error instance. */
  data$: ComAtprotoSyncGetBlobBadRequestErrorData;

  constructor(
    err: ComAtprotoSyncGetBlobBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ComAtprotoSyncGetBlobBadRequestError";
  }
}

/** @internal */
export const ComAtprotoSyncGetBlobAuthMissingError$inboundSchema: z.ZodType<
  ComAtprotoSyncGetBlobAuthMissingError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.literal("AuthMissing"),
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ComAtprotoSyncGetBlobAuthMissingError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ComAtprotoSyncGetBlobAuthMissingError$Outbound = {
  error: "AuthMissing";
  message: string;
};

/** @internal */
export const ComAtprotoSyncGetBlobAuthMissingError$outboundSchema: z.ZodType<
  ComAtprotoSyncGetBlobAuthMissingError$Outbound,
  z.ZodTypeDef,
  ComAtprotoSyncGetBlobAuthMissingError
> = z.instanceof(ComAtprotoSyncGetBlobAuthMissingError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.literal("AuthMissing"),
    message: z.string(),
  }));

/** @internal */
export const ComAtprotoSyncGetBlobError$inboundSchema: z.ZodNativeEnum<
  typeof ComAtprotoSyncGetBlobError
> = z.nativeEnum(ComAtprotoSyncGetBlobError);
/** @internal */
export const ComAtprotoSyncGetBlobError$outboundSchema: z.ZodNativeEnum<
  typeof ComAtprotoSyncGetBlobError
> = ComAtprotoSyncGetBlobError$inboundSchema;

/** @internal */
export const ComAtprotoSyncGetBlobBadRequestError$inboundSchema: z.ZodType<
  ComAtprotoSyncGetBlobBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: ComAtprotoSyncGetBlobError$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ComAtprotoSyncGetBlobBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ComAtprotoSyncGetBlobBadRequestError$Outbound = {
  error: string;
  message: string;
};

/** @internal */
export const ComAtprotoSyncGetBlobBadRequestError$outboundSchema: z.ZodType<
  ComAtprotoSyncGetBlobBadRequestError$Outbound,
  z.ZodTypeDef,
  ComAtprotoSyncGetBlobBadRequestError
> = z.instanceof(ComAtprotoSyncGetBlobBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: ComAtprotoSyncGetBlobError$outboundSchema,
    message: z.string(),
  }));
