/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { collectExtraKeys as collectExtraKeys$ } from "../../lib/schemas.js";

/**
 * Status codes relating to the client being rate limited by the server
 */
export type RateLimitedErrorData = {
  message?: string | undefined;

  additionalProperties: { [k: string]: any };
};

/**
 * Status codes relating to the client being rate limited by the server
 */
export class RateLimitedError extends Error {
  additionalProperties: { [k: string]: any } = {};

  /** The original data that was passed to this error instance. */
  data$: RateLimitedErrorData;

  constructor(err: RateLimitedErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.additionalProperties != null) {
      this.additionalProperties = err.additionalProperties;
    }

    this.name = "RateLimitedError";
  }
}

/** @internal */
export const RateLimitedError$inboundSchema: z.ZodType<
  RateLimitedError,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    message: z.string().optional(),
  })
    .catchall(z.any()),
  "additionalProperties",
  true,
)
  .transform((v) => {
    return new RateLimitedError(v);
  });

/** @internal */
export type RateLimitedError$Outbound = {
  message?: string | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const RateLimitedError$outboundSchema: z.ZodType<
  RateLimitedError$Outbound,
  z.ZodTypeDef,
  RateLimitedError
> = z.instanceof(RateLimitedError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      message: z.string().optional(),
      additionalProperties: z.record(z.any()),
    }).transform((v) => {
      return {
        ...v.additionalProperties,
        ...remap$(v, {
          additionalProperties: null,
        }),
      };
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RateLimitedError$ {
  /** @deprecated use `RateLimitedError$inboundSchema` instead. */
  export const inboundSchema = RateLimitedError$inboundSchema;
  /** @deprecated use `RateLimitedError$outboundSchema` instead. */
  export const outboundSchema = RateLimitedError$outboundSchema;
  /** @deprecated use `RateLimitedError$Outbound` instead. */
  export type Outbound = RateLimitedError$Outbound;
}
