/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Unauthorized
 */
export type UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyErrorData =
  {
    error: "AuthMissing";
    message: string;
  };

/**
 * Unauthorized
 */
export class UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError
  extends Error
{
  error: "AuthMissing";

  /** The original data that was passed to this error instance. */
  data$: UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyErrorData;

  constructor(
    err: UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyErrorData,
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name =
      "UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError";
  }
}

export const ToolsOzoneCommunicationDeleteTemplateError = {
  InvalidRequest: "InvalidRequest",
  ExpiredToken: "ExpiredToken",
  InvalidToken: "InvalidToken",
} as const;
export type ToolsOzoneCommunicationDeleteTemplateError = ClosedEnum<
  typeof ToolsOzoneCommunicationDeleteTemplateError
>;

/**
 * Bad Request
 */
export type BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyErrorData =
  {
    error: ToolsOzoneCommunicationDeleteTemplateError;
    message: string;
  };

/**
 * Bad Request
 */
export class BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError
  extends Error
{
  error: ToolsOzoneCommunicationDeleteTemplateError;

  /** The original data that was passed to this error instance. */
  data$: BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyErrorData;

  constructor(
    err: BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyErrorData,
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name =
      "BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError";
  }
}

/** @internal */
export const UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError$inboundSchema:
  z.ZodType<
    UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.literal("AuthMissing"),
    message: z.string(),
  })
    .transform((v) => {
      return new UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError(
        v,
      );
    });

/** @internal */
export type UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError$Outbound =
  {
    error: "AuthMissing";
    message: string;
  };

/** @internal */
export const UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError$outboundSchema:
  z.ZodType<
    UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError$Outbound,
    z.ZodTypeDef,
    UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError
  > = z.instanceof(
    UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.literal("AuthMissing").default("AuthMissing" as const),
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError$ {
  /** @deprecated use `UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError$inboundSchema` instead. */
  export const inboundSchema =
    UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError$inboundSchema;
  /** @deprecated use `UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError$outboundSchema` instead. */
  export const outboundSchema =
    UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError$outboundSchema;
  /** @deprecated use `UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError$Outbound` instead. */
  export type Outbound =
    UnauthorizedToolsOzoneCommunicationDeleteTemplateResponseBodyError$Outbound;
}

/** @internal */
export const ToolsOzoneCommunicationDeleteTemplateError$inboundSchema:
  z.ZodNativeEnum<typeof ToolsOzoneCommunicationDeleteTemplateError> = z
    .nativeEnum(ToolsOzoneCommunicationDeleteTemplateError);

/** @internal */
export const ToolsOzoneCommunicationDeleteTemplateError$outboundSchema:
  z.ZodNativeEnum<typeof ToolsOzoneCommunicationDeleteTemplateError> =
    ToolsOzoneCommunicationDeleteTemplateError$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ToolsOzoneCommunicationDeleteTemplateError$ {
  /** @deprecated use `ToolsOzoneCommunicationDeleteTemplateError$inboundSchema` instead. */
  export const inboundSchema =
    ToolsOzoneCommunicationDeleteTemplateError$inboundSchema;
  /** @deprecated use `ToolsOzoneCommunicationDeleteTemplateError$outboundSchema` instead. */
  export const outboundSchema =
    ToolsOzoneCommunicationDeleteTemplateError$outboundSchema;
}

/** @internal */
export const BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError$inboundSchema:
  z.ZodType<
    BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: ToolsOzoneCommunicationDeleteTemplateError$inboundSchema,
    message: z.string(),
  })
    .transform((v) => {
      return new BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError(
        v,
      );
    });

/** @internal */
export type BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError$Outbound =
  {
    error: string;
    message: string;
  };

/** @internal */
export const BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError$outboundSchema:
  z.ZodType<
    BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError$Outbound,
    z.ZodTypeDef,
    BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError
  > = z.instanceof(
    BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      error: ToolsOzoneCommunicationDeleteTemplateError$outboundSchema,
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError$ {
  /** @deprecated use `BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError$inboundSchema` instead. */
  export const inboundSchema =
    BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError$inboundSchema;
  /** @deprecated use `BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError$outboundSchema` instead. */
  export const outboundSchema =
    BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError$outboundSchema;
  /** @deprecated use `BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError$Outbound` instead. */
  export type Outbound =
    BadRequestToolsOzoneCommunicationDeleteTemplateResponseBodyError$Outbound;
}
