/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { BlueskyCore } from "../core.js";
import { atprotoAdminGetAccountInfos } from "../funcs/atprotoAdminGetAccountInfos.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useBlueskyContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type AtprotoAdminGetAccountInfosQueryData =
  operations.ComAtprotoAdminGetAccountInfosResponseBody;

/**
 * *This endpoint is part of the atproto PDS management APIs. Requests usually require admin authentication and are made directly to the PDS instance.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Get details about some accounts.
 */
export function useAtprotoAdminGetAccountInfos(
  request: operations.ComAtprotoAdminGetAccountInfosRequest,
  options?: QueryHookOptions<
    operations.ComAtprotoAdminGetAccountInfosResponseBody
  >,
): UseQueryResult<
  operations.ComAtprotoAdminGetAccountInfosResponseBody,
  Error
> {
  const client = useBlueskyContext();
  return useQuery({
    ...buildAtprotoAdminGetAccountInfosQuery(
      client,
      request,
      options?.request,
    ),
    ...options,
  });
}

/**
 * *This endpoint is part of the atproto PDS management APIs. Requests usually require admin authentication and are made directly to the PDS instance.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Get details about some accounts.
 */
export function useAtprotoAdminGetAccountInfosSuspense(
  request: operations.ComAtprotoAdminGetAccountInfosRequest,
  options?: SuspenseQueryHookOptions<
    operations.ComAtprotoAdminGetAccountInfosResponseBody
  >,
): UseSuspenseQueryResult<
  operations.ComAtprotoAdminGetAccountInfosResponseBody,
  Error
> {
  const client = useBlueskyContext();
  return useSuspenseQuery({
    ...buildAtprotoAdminGetAccountInfosQuery(
      client,
      request,
      options?.request,
    ),
    ...options,
  });
}

export function prefetchAtprotoAdminGetAccountInfos(
  queryClient: QueryClient,
  client$: BlueskyCore,
  request: operations.ComAtprotoAdminGetAccountInfosRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildAtprotoAdminGetAccountInfosQuery(
      client$,
      request,
    ),
  });
}

export function setAtprotoAdminGetAccountInfosData(
  client: QueryClient,
  queryKeyBase: [parameters: { dids: Array<string> }],
  data: operations.ComAtprotoAdminGetAccountInfosResponseBody,
): operations.ComAtprotoAdminGetAccountInfosResponseBody | undefined {
  const key = queryKeyAtprotoAdminGetAccountInfos(...queryKeyBase);

  return client.setQueryData<
    operations.ComAtprotoAdminGetAccountInfosResponseBody
  >(key, data);
}

export function invalidateAtprotoAdminGetAccountInfos(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[parameters: { dids: Array<string> }]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["bluesky", "admin", "getAccountInfos", ...queryKeyBase],
  });
}

export function invalidateAllAtprotoAdminGetAccountInfos(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["bluesky", "admin", "getAccountInfos"],
  });
}

export function buildAtprotoAdminGetAccountInfosQuery(
  client$: BlueskyCore,
  request: operations.ComAtprotoAdminGetAccountInfosRequest,
  options?: RequestOptions,
): {
  retry: boolean;
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<operations.ComAtprotoAdminGetAccountInfosResponseBody>;
} {
  return {
    retry: false,
    queryKey: queryKeyAtprotoAdminGetAccountInfos({ dids: request.dids }),
    queryFn: async function atprotoAdminGetAccountInfosQuery(
      ctx,
    ): Promise<operations.ComAtprotoAdminGetAccountInfosResponseBody> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(atprotoAdminGetAccountInfos(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyAtprotoAdminGetAccountInfos(
  parameters: { dids: Array<string> },
): QueryKey {
  return ["bluesky", "admin", "getAccountInfos", parameters];
}
