/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { BlueskyCore } from "../core.js";
import { atprotoAdminGetAccountInfo } from "../funcs/atprotoAdminGetAccountInfo.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useBlueskyContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type AtprotoAdminGetAccountInfoQueryData =
  components.ComAtprotoAdminDefsAccountView;

/**
 * *This endpoint is part of the atproto PDS management APIs. Requests usually require admin authentication and are made directly to the PDS instance.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Get details about an account.
 */
export function useAtprotoAdminGetAccountInfo(
  request: operations.ComAtprotoAdminGetAccountInfoRequest,
  options?: QueryHookOptions<components.ComAtprotoAdminDefsAccountView>,
): UseQueryResult<components.ComAtprotoAdminDefsAccountView, Error> {
  const client = useBlueskyContext();
  return useQuery({
    ...buildAtprotoAdminGetAccountInfoQuery(
      client,
      request,
      options?.request,
    ),
    ...options,
  });
}

/**
 * *This endpoint is part of the atproto PDS management APIs. Requests usually require admin authentication and are made directly to the PDS instance.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Get details about an account.
 */
export function useAtprotoAdminGetAccountInfoSuspense(
  request: operations.ComAtprotoAdminGetAccountInfoRequest,
  options?: SuspenseQueryHookOptions<components.ComAtprotoAdminDefsAccountView>,
): UseSuspenseQueryResult<components.ComAtprotoAdminDefsAccountView, Error> {
  const client = useBlueskyContext();
  return useSuspenseQuery({
    ...buildAtprotoAdminGetAccountInfoQuery(
      client,
      request,
      options?.request,
    ),
    ...options,
  });
}

export function prefetchAtprotoAdminGetAccountInfo(
  queryClient: QueryClient,
  client$: BlueskyCore,
  request: operations.ComAtprotoAdminGetAccountInfoRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildAtprotoAdminGetAccountInfoQuery(
      client$,
      request,
    ),
  });
}

export function setAtprotoAdminGetAccountInfoData(
  client: QueryClient,
  queryKeyBase: [parameters: { did: string }],
  data: components.ComAtprotoAdminDefsAccountView,
): components.ComAtprotoAdminDefsAccountView | undefined {
  const key = queryKeyAtprotoAdminGetAccountInfo(...queryKeyBase);

  return client.setQueryData<components.ComAtprotoAdminDefsAccountView>(
    key,
    data,
  );
}

export function invalidateAtprotoAdminGetAccountInfo(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[parameters: { did: string }]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["bluesky", "admin", "getAccountInfo", ...queryKeyBase],
  });
}

export function invalidateAllAtprotoAdminGetAccountInfo(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["bluesky", "admin", "getAccountInfo"],
  });
}

export function buildAtprotoAdminGetAccountInfoQuery(
  client$: BlueskyCore,
  request: operations.ComAtprotoAdminGetAccountInfoRequest,
  options?: RequestOptions,
): {
  retry: boolean;
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<components.ComAtprotoAdminDefsAccountView>;
} {
  return {
    retry: false,
    queryKey: queryKeyAtprotoAdminGetAccountInfo({ did: request.did }),
    queryFn: async function atprotoAdminGetAccountInfoQuery(
      ctx,
    ): Promise<components.ComAtprotoAdminDefsAccountView> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(atprotoAdminGetAccountInfo(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyAtprotoAdminGetAccountInfo(
  parameters: { did: string },
): QueryKey {
  return ["bluesky", "admin", "getAccountInfo", parameters];
}
