/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { BlueskyCore } from "../core.js";
import { atprotoAdminUpdateAccountHandle } from "../funcs/atprotoAdminUpdateAccountHandle.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useBlueskyContext } from "./_context.js";

export type AtprotoAdminUpdateAccountHandleMutationVariables = {
  request: operations.ComAtprotoAdminUpdateAccountHandleRequestBody;
  options?: RequestOptions;
};

/**
 * *This endpoint is part of the atproto PDS management APIs. Requests usually require admin authentication and are made directly to the PDS instance.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Administrative action to update an account's handle.
 */
export function useAtprotoAdminUpdateAccountHandleMutation(
  options?: UseMutationOptions<
    void,
    Error,
    AtprotoAdminUpdateAccountHandleMutationVariables
  >,
): UseMutationResult<
  void,
  Error,
  AtprotoAdminUpdateAccountHandleMutationVariables
> {
  const client = useBlueskyContext();
  return useMutation({
    ...buildAtprotoAdminUpdateAccountHandleMutation(client),
    ...options,
  });
}

export function mutationKeyAtprotoAdminUpdateAccountHandle(): MutationKey {
  return ["bluesky", "admin", "updateAccountHandle"];
}

export function buildAtprotoAdminUpdateAccountHandleMutation(
  client$: BlueskyCore,
): {
  retry: boolean;
  mutationKey: MutationKey;
  mutationFn: (
    variables: AtprotoAdminUpdateAccountHandleMutationVariables,
  ) => Promise<void>;
} {
  return {
    retry: false,
    mutationKey: mutationKeyAtprotoAdminUpdateAccountHandle(),
    mutationFn: function atprotoAdminUpdateAccountHandleQuery({
      request,
      options,
    }): Promise<void> {
      return unwrapAsync(atprotoAdminUpdateAccountHandle(
        client$,
        request,
        options,
      ));
    },
  };
}
