/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { BlueskyCore } from "../core.js";
import { atprotoServerRefreshSession } from "../funcs/atprotoServerRefreshSession.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useBlueskyContext } from "./_context.js";

export type AtprotoServerRefreshSessionMutationVariables = {
  options?: RequestOptions;
};

/**
 * *This endpoint is part of the atproto PDS server and account management APIs. Requests often require authentication and are made directly to the user's own PDS instance.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Refresh an authentication session. Requires auth using the 'refreshJwt' (not the 'accessJwt').
 */
export function useAtprotoServerRefreshSessionMutation(
  options?: UseMutationOptions<
    operations.ComAtprotoServerRefreshSessionResponseBody,
    Error,
    AtprotoServerRefreshSessionMutationVariables
  >,
): UseMutationResult<
  operations.ComAtprotoServerRefreshSessionResponseBody,
  Error,
  AtprotoServerRefreshSessionMutationVariables
> {
  const client = useBlueskyContext();
  return useMutation({
    ...buildAtprotoServerRefreshSessionMutation(client),
    ...options,
  });
}

export function mutationKeyAtprotoServerRefreshSession(): MutationKey {
  return ["bluesky", "server", "refreshSession"];
}

export function buildAtprotoServerRefreshSessionMutation(
  client$: BlueskyCore,
): {
  retry: boolean;
  mutationKey: MutationKey;
  mutationFn: (
    variables: AtprotoServerRefreshSessionMutationVariables,
  ) => Promise<operations.ComAtprotoServerRefreshSessionResponseBody>;
} {
  return {
    retry: false,
    mutationKey: mutationKeyAtprotoServerRefreshSession(),
    mutationFn: function atprotoServerRefreshSessionQuery({
      options,
    }): Promise<operations.ComAtprotoServerRefreshSessionResponseBody> {
      return unwrapAsync(atprotoServerRefreshSession(
        client$,
        options,
      ));
    },
  };
}
