/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { BlueskyCore } from "../core.js";
import { atprotoServerDeleteAccount } from "../funcs/atprotoServerDeleteAccount.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useBlueskyContext } from "./_context.js";

export type AtprotoServerDeleteAccountMutationVariables = {
  request: operations.ComAtprotoServerDeleteAccountRequestBody;
  options?: RequestOptions;
};

/**
 * *This endpoint is part of the atproto PDS server and account management APIs. Requests often require authentication and are made directly to the user's own PDS instance.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Delete an actor's account with a token and password. Can only be called after requesting a deletion token. Requires auth.
 */
export function useAtprotoServerDeleteAccountMutation(
  options?: UseMutationOptions<
    void,
    Error,
    AtprotoServerDeleteAccountMutationVariables
  >,
): UseMutationResult<void, Error, AtprotoServerDeleteAccountMutationVariables> {
  const client = useBlueskyContext();
  return useMutation({
    ...buildAtprotoServerDeleteAccountMutation(client),
    ...options,
  });
}

export function mutationKeyAtprotoServerDeleteAccount(): MutationKey {
  return ["bluesky", "server", "deleteAccount"];
}

export function buildAtprotoServerDeleteAccountMutation(
  client$: BlueskyCore,
): {
  retry: boolean;
  mutationKey: MutationKey;
  mutationFn: (
    variables: AtprotoServerDeleteAccountMutationVariables,
  ) => Promise<void>;
} {
  return {
    retry: false,
    mutationKey: mutationKeyAtprotoServerDeleteAccount(),
    mutationFn: function atprotoServerDeleteAccountQuery({
      request,
      options,
    }): Promise<void> {
      return unwrapAsync(atprotoServerDeleteAccount(
        client$,
        request,
        options,
      ));
    },
  };
}
