/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InfiniteData,
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useInfiniteQuery,
  UseInfiniteQueryResult,
  useQuery,
  UseQueryResult,
  useSuspenseInfiniteQuery,
  UseSuspenseInfiniteQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { BlueskyCore } from "../core.js";
import { graphsGetKnownFollowers } from "../funcs/graphsGetKnownFollowers.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";
import { useBlueskyContext } from "./_context.js";
import {
  InfiniteQueryHookOptions,
  QueryHookOptions,
  SuspenseInfiniteQueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type GraphsGetKnownFollowersQueryData =
  operations.AppBskyGraphGetKnownFollowersResponse;

export type GraphsGetKnownFollowersInfiniteQueryData = PageIterator<
  operations.AppBskyGraphGetKnownFollowersResponse,
  { cursor: string }
>;

export type GraphsGetKnownFollowersPageParams = PageIterator<
  operations.AppBskyGraphGetKnownFollowersResponse,
  { cursor: string }
>["~next"];

/**
 * *This endpoint is part of the Bluesky application Lexicon APIs (`app.bsky.*`). Public endpoints which don't require authentication can be made directly against the public Bluesky AppView API: https://public.api.bsky.app. Authenticated requests are usually made to the user's PDS, with automatic service proxying. Authenticated requests can be used for both public and non-public endpoints.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Enumerates accounts which follow a specified account (actor) and are followed by the viewer.
 */
export function useGraphsGetKnownFollowers(
  request: operations.AppBskyGraphGetKnownFollowersRequest,
  options?: QueryHookOptions<GraphsGetKnownFollowersQueryData>,
): UseQueryResult<GraphsGetKnownFollowersQueryData, Error> {
  const client = useBlueskyContext();
  return useQuery({
    ...buildGraphsGetKnownFollowersQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * *This endpoint is part of the Bluesky application Lexicon APIs (`app.bsky.*`). Public endpoints which don't require authentication can be made directly against the public Bluesky AppView API: https://public.api.bsky.app. Authenticated requests are usually made to the user's PDS, with automatic service proxying. Authenticated requests can be used for both public and non-public endpoints.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Enumerates accounts which follow a specified account (actor) and are followed by the viewer.
 */
export function useGraphsGetKnownFollowersSuspense(
  request: operations.AppBskyGraphGetKnownFollowersRequest,
  options?: SuspenseQueryHookOptions<GraphsGetKnownFollowersQueryData>,
): UseSuspenseQueryResult<GraphsGetKnownFollowersQueryData, Error> {
  const client = useBlueskyContext();
  return useSuspenseQuery({
    ...buildGraphsGetKnownFollowersQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * *This endpoint is part of the Bluesky application Lexicon APIs (`app.bsky.*`). Public endpoints which don't require authentication can be made directly against the public Bluesky AppView API: https://public.api.bsky.app. Authenticated requests are usually made to the user's PDS, with automatic service proxying. Authenticated requests can be used for both public and non-public endpoints.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Enumerates accounts which follow a specified account (actor) and are followed by the viewer.
 */
export function useGraphsGetKnownFollowersInfinite(
  request: operations.AppBskyGraphGetKnownFollowersRequest,
  options?: InfiniteQueryHookOptions<GraphsGetKnownFollowersInfiniteQueryData>,
): UseInfiniteQueryResult<
  InfiniteData<
    GraphsGetKnownFollowersInfiniteQueryData,
    GraphsGetKnownFollowersPageParams
  >,
  Error
> {
  const client = useBlueskyContext();
  return useInfiniteQuery<
    GraphsGetKnownFollowersInfiniteQueryData,
    Error,
    InfiniteData<
      GraphsGetKnownFollowersInfiniteQueryData,
      GraphsGetKnownFollowersPageParams
    >,
    QueryKey,
    GraphsGetKnownFollowersPageParams
  >({
    ...buildGraphsGetKnownFollowersInfiniteQuery(
      client,
      request,
      options,
    ),
    initialPageParam: options?.initialPageParam,
    getNextPageParam: (previousPage) => previousPage["~next"],
    ...options,
  });
}

/**
 * *This endpoint is part of the Bluesky application Lexicon APIs (`app.bsky.*`). Public endpoints which don't require authentication can be made directly against the public Bluesky AppView API: https://public.api.bsky.app. Authenticated requests are usually made to the user's PDS, with automatic service proxying. Authenticated requests can be used for both public and non-public endpoints.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Enumerates accounts which follow a specified account (actor) and are followed by the viewer.
 */
export function useGraphsGetKnownFollowersInfiniteSuspense(
  request: operations.AppBskyGraphGetKnownFollowersRequest,
  options?: SuspenseInfiniteQueryHookOptions<
    GraphsGetKnownFollowersInfiniteQueryData
  >,
): UseSuspenseInfiniteQueryResult<
  InfiniteData<
    GraphsGetKnownFollowersInfiniteQueryData,
    GraphsGetKnownFollowersPageParams
  >,
  Error
> {
  const client = useBlueskyContext();
  return useSuspenseInfiniteQuery<
    GraphsGetKnownFollowersInfiniteQueryData,
    Error,
    InfiniteData<
      GraphsGetKnownFollowersInfiniteQueryData,
      GraphsGetKnownFollowersPageParams
    >,
    QueryKey,
    GraphsGetKnownFollowersPageParams
  >({
    ...buildGraphsGetKnownFollowersInfiniteQuery(
      client,
      request,
      options,
    ),
    initialPageParam: options?.initialPageParam,
    getNextPageParam: (previousPage) => previousPage["~next"],
    ...options,
  });
}

export function prefetchGraphsGetKnownFollowers(
  queryClient: QueryClient,
  client$: BlueskyCore,
  request: operations.AppBskyGraphGetKnownFollowersRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildGraphsGetKnownFollowersQuery(
      client$,
      request,
    ),
  });
}

export function setGraphsGetKnownFollowersData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      actor: string;
      limit?: number | undefined;
      cursor?: string | undefined;
    },
  ],
  data: GraphsGetKnownFollowersQueryData,
): GraphsGetKnownFollowersQueryData | undefined {
  const key = queryKeyGraphsGetKnownFollowers(...queryKeyBase);

  return client.setQueryData<GraphsGetKnownFollowersQueryData>(key, data);
}

export function invalidateGraphsGetKnownFollowers(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      actor: string;
      limit?: number | undefined;
      cursor?: string | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/bluesky",
      "graphs",
      "getKnownFollowers",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllGraphsGetKnownFollowers(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@speakeasy-api/bluesky", "graphs", "getKnownFollowers"],
  });
}

export function buildGraphsGetKnownFollowersQuery(
  client$: BlueskyCore,
  request: operations.AppBskyGraphGetKnownFollowersRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<GraphsGetKnownFollowersQueryData>;
} {
  return {
    queryKey: queryKeyGraphsGetKnownFollowers({
      actor: request.actor,
      limit: request.limit,
      cursor: request.cursor,
    }),
    queryFn: async function graphsGetKnownFollowersQueryFn(
      ctx,
    ): Promise<GraphsGetKnownFollowersQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(graphsGetKnownFollowers(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function buildGraphsGetKnownFollowersInfiniteQuery(
  client$: BlueskyCore,
  request: operations.AppBskyGraphGetKnownFollowersRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext<QueryKey, GraphsGetKnownFollowersPageParams>,
  ) => Promise<GraphsGetKnownFollowersInfiniteQueryData>;
} {
  return {
    queryKey: queryKeyGraphsGetKnownFollowers({
      actor: request.actor,
      limit: request.limit,
      cursor: request.cursor,
    }),
    queryFn: async function graphsGetKnownFollowersQuery(
      ctx,
    ): Promise<GraphsGetKnownFollowersInfiniteQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      if (!ctx.pageParam) {
        return unwrapResultIterator(graphsGetKnownFollowers(
          client$,
          request,
          mergedOptions,
        ));
      }

      return unwrapResultIterator(graphsGetKnownFollowers(
        client$,
        {
          ...request,
          cursor: ctx.pageParam.cursor,
        },
        mergedOptions,
      ));
    },
  };
}

export function queryKeyGraphsGetKnownFollowers(
  parameters: {
    actor: string;
    limit?: number | undefined;
    cursor?: string | undefined;
  },
): QueryKey {
  return ["@speakeasy-api/bluesky", "graphs", "getKnownFollowers", parameters];
}
