/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { BlueskyCore } from "../core.js";
import { notificationsUpdateSeen } from "../funcs/notificationsUpdateSeen.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useBlueskyContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type NotificationsUpdateSeenMutationVariables = {
  request: operations.AppBskyNotificationUpdateSeenBody;
  options?: RequestOptions;
};

export type NotificationsUpdateSeenMutationData = void;

/**
 * *This endpoint is part of the Bluesky application Lexicon APIs (`app.bsky.*`). Public endpoints which don't require authentication can be made directly against the public Bluesky AppView API: https://public.api.bsky.app. Authenticated requests are usually made to the user's PDS, with automatic service proxying. Authenticated requests can be used for both public and non-public endpoints.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Notify server that the requesting account has seen notifications. Requires auth.
 */
export function useNotificationsUpdateSeenMutation(
  options?: MutationHookOptions<
    NotificationsUpdateSeenMutationData,
    Error,
    NotificationsUpdateSeenMutationVariables
  >,
): UseMutationResult<
  NotificationsUpdateSeenMutationData,
  Error,
  NotificationsUpdateSeenMutationVariables
> {
  const client = useBlueskyContext();
  return useMutation({
    ...buildNotificationsUpdateSeenMutation(client, options),
    ...options,
  });
}

export function mutationKeyNotificationsUpdateSeen(): MutationKey {
  return ["@speakeasy-api/bluesky", "notifications", "updateSeen"];
}

export function buildNotificationsUpdateSeenMutation(
  client$: BlueskyCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: NotificationsUpdateSeenMutationVariables,
  ) => Promise<NotificationsUpdateSeenMutationData>;
} {
  return {
    mutationKey: mutationKeyNotificationsUpdateSeen(),
    mutationFn: function notificationsUpdateSeenMutationFn({
      request,
      options,
    }): Promise<NotificationsUpdateSeenMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(notificationsUpdateSeen(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
