/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InfiniteData,
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useInfiniteQuery,
  UseInfiniteQueryResult,
  useQuery,
  UseQueryResult,
  useSuspenseInfiniteQuery,
  UseSuspenseInfiniteQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { BlueskyCore } from "../core.js";
import { actorsSearch } from "../funcs/actorsSearch.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";
import { useBlueskyContext } from "./_context.js";
import {
  InfiniteQueryHookOptions,
  QueryHookOptions,
  SuspenseInfiniteQueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type SearchActorsQueryData = operations.AppBskyActorSearchActorsResponse;

export type SearchActorsInfiniteQueryData = PageIterator<
  operations.AppBskyActorSearchActorsResponse,
  { cursor: string }
>;

export type SearchActorsPageParams = PageIterator<
  operations.AppBskyActorSearchActorsResponse,
  { cursor: string }
>["~next"];

/**
 * *This endpoint is part of the Bluesky application Lexicon APIs (`app.bsky.*`). Public endpoints which don't require authentication can be made directly against the public Bluesky AppView API: https://public.api.bsky.app. Authenticated requests are usually made to the user's PDS, with automatic service proxying. Authenticated requests can be used for both public and non-public endpoints.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Find actors (profiles) matching search criteria. Does not require auth.
 */
export function useSearchActors(
  request?: operations.AppBskyActorSearchActorsRequest | undefined,
  options?: QueryHookOptions<SearchActorsQueryData>,
): UseQueryResult<SearchActorsQueryData, Error> {
  const client = useBlueskyContext();
  return useQuery({
    ...buildSearchActorsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * *This endpoint is part of the Bluesky application Lexicon APIs (`app.bsky.*`). Public endpoints which don't require authentication can be made directly against the public Bluesky AppView API: https://public.api.bsky.app. Authenticated requests are usually made to the user's PDS, with automatic service proxying. Authenticated requests can be used for both public and non-public endpoints.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Find actors (profiles) matching search criteria. Does not require auth.
 */
export function useSearchActorsSuspense(
  request?: operations.AppBskyActorSearchActorsRequest | undefined,
  options?: SuspenseQueryHookOptions<SearchActorsQueryData>,
): UseSuspenseQueryResult<SearchActorsQueryData, Error> {
  const client = useBlueskyContext();
  return useSuspenseQuery({
    ...buildSearchActorsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * *This endpoint is part of the Bluesky application Lexicon APIs (`app.bsky.*`). Public endpoints which don't require authentication can be made directly against the public Bluesky AppView API: https://public.api.bsky.app. Authenticated requests are usually made to the user's PDS, with automatic service proxying. Authenticated requests can be used for both public and non-public endpoints.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Find actors (profiles) matching search criteria. Does not require auth.
 */
export function useSearchActorsInfinite(
  request?: operations.AppBskyActorSearchActorsRequest | undefined,
  options?: InfiniteQueryHookOptions<SearchActorsInfiniteQueryData>,
): UseInfiniteQueryResult<
  InfiniteData<SearchActorsInfiniteQueryData, SearchActorsPageParams>,
  Error
> {
  const client = useBlueskyContext();
  return useInfiniteQuery<
    SearchActorsInfiniteQueryData,
    Error,
    InfiniteData<SearchActorsInfiniteQueryData, SearchActorsPageParams>,
    QueryKey,
    SearchActorsPageParams
  >({
    ...buildSearchActorsInfiniteQuery(
      client,
      request,
      options,
    ),
    initialPageParam: options?.initialPageParam,
    getNextPageParam: (previousPage) => previousPage["~next"],
    ...options,
  });
}

/**
 * *This endpoint is part of the Bluesky application Lexicon APIs (`app.bsky.*`). Public endpoints which don't require authentication can be made directly against the public Bluesky AppView API: https://public.api.bsky.app. Authenticated requests are usually made to the user's PDS, with automatic service proxying. Authenticated requests can be used for both public and non-public endpoints.*
 *
 * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
 *
 * Find actors (profiles) matching search criteria. Does not require auth.
 */
export function useSearchActorsInfiniteSuspense(
  request?: operations.AppBskyActorSearchActorsRequest | undefined,
  options?: SuspenseInfiniteQueryHookOptions<SearchActorsInfiniteQueryData>,
): UseSuspenseInfiniteQueryResult<
  InfiniteData<SearchActorsInfiniteQueryData, SearchActorsPageParams>,
  Error
> {
  const client = useBlueskyContext();
  return useSuspenseInfiniteQuery<
    SearchActorsInfiniteQueryData,
    Error,
    InfiniteData<SearchActorsInfiniteQueryData, SearchActorsPageParams>,
    QueryKey,
    SearchActorsPageParams
  >({
    ...buildSearchActorsInfiniteQuery(
      client,
      request,
      options,
    ),
    initialPageParam: options?.initialPageParam,
    getNextPageParam: (previousPage) => previousPage["~next"],
    ...options,
  });
}

export function prefetchSearchActors(
  queryClient: QueryClient,
  client$: BlueskyCore,
  request?: operations.AppBskyActorSearchActorsRequest | undefined,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildSearchActorsQuery(
      client$,
      request,
    ),
  });
}

export function setSearchActorsData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      q?: string | undefined;
      limit?: number | undefined;
      cursor?: string | undefined;
    },
  ],
  data: SearchActorsQueryData,
): SearchActorsQueryData | undefined {
  const key = queryKeySearchActors(...queryKeyBase);

  return client.setQueryData<SearchActorsQueryData>(key, data);
}

export function invalidateSearchActors(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      q?: string | undefined;
      limit?: number | undefined;
      cursor?: string | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@speakeasy-sdks/bluesky", "actors", "search", ...queryKeyBase],
  });
}

export function invalidateAllSearchActors(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@speakeasy-sdks/bluesky", "actors", "search"],
  });
}

export function buildSearchActorsQuery(
  client$: BlueskyCore,
  request?: operations.AppBskyActorSearchActorsRequest | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<SearchActorsQueryData>;
} {
  return {
    queryKey: queryKeySearchActors({
      q: request?.q,
      limit: request?.limit,
      cursor: request?.cursor,
    }),
    queryFn: async function searchActorsQueryFn(
      ctx,
    ): Promise<SearchActorsQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(actorsSearch(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function buildSearchActorsInfiniteQuery(
  client$: BlueskyCore,
  request?: operations.AppBskyActorSearchActorsRequest | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext<QueryKey, SearchActorsPageParams>,
  ) => Promise<SearchActorsInfiniteQueryData>;
} {
  return {
    queryKey: queryKeySearchActors({
      q: request?.q,
      limit: request?.limit,
      cursor: request?.cursor,
    }),
    queryFn: async function searchActorsQuery(
      ctx,
    ): Promise<SearchActorsInfiniteQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      if (!ctx.pageParam) {
        return unwrapResultIterator(actorsSearch(
          client$,
          request,
          mergedOptions,
        ));
      }

      return unwrapResultIterator(actorsSearch(
        client$,
        {
          ...request,
          cursor: ctx.pageParam.cursor,
        },
        mergedOptions,
      ));
    },
  };
}

export function queryKeySearchActors(
  parameters: {
    q?: string | undefined;
    limit?: number | undefined;
    cursor?: string | undefined;
  },
): QueryKey {
  return ["@speakeasy-sdks/bluesky", "actors", "search", parameters];
}
