/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { chatBskyConvoChatBskyConvoDeleteMessageForSelf } from "../funcs/chatBskyConvoChatBskyConvoDeleteMessageForSelf.js";
import { chatBskyConvoChatBskyConvoGetConvo } from "../funcs/chatBskyConvoChatBskyConvoGetConvo.js";
import { chatBskyConvoChatBskyConvoGetConvoForMembers } from "../funcs/chatBskyConvoChatBskyConvoGetConvoForMembers.js";
import { chatBskyConvoChatBskyConvoGetLog } from "../funcs/chatBskyConvoChatBskyConvoGetLog.js";
import { chatBskyConvoChatBskyConvoGetMessages } from "../funcs/chatBskyConvoChatBskyConvoGetMessages.js";
import { chatBskyConvoChatBskyConvoLeaveConvo } from "../funcs/chatBskyConvoChatBskyConvoLeaveConvo.js";
import { chatBskyConvoChatBskyConvoListConvos } from "../funcs/chatBskyConvoChatBskyConvoListConvos.js";
import { chatBskyConvoChatBskyConvoMuteConvo } from "../funcs/chatBskyConvoChatBskyConvoMuteConvo.js";
import { chatBskyConvoChatBskyConvoSendMessage } from "../funcs/chatBskyConvoChatBskyConvoSendMessage.js";
import { chatBskyConvoChatBskyConvoSendMessageBatch } from "../funcs/chatBskyConvoChatBskyConvoSendMessageBatch.js";
import { chatBskyConvoChatBskyConvoUnmuteConvo } from "../funcs/chatBskyConvoChatBskyConvoUnmuteConvo.js";
import { chatBskyConvoChatBskyConvoUpdateRead } from "../funcs/chatBskyConvoChatBskyConvoUpdateRead.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Convo extends ClientSDK {
  /**
   * *This endpoint is part of the Bluesky Chat (DMs) APIs. Requests usually require authentication, are directed to the user's PDS intance, and proxied to the single central chat service by setting the appropriate service DID (`did:web:api.bsky.chat`) in the service proxying header.*
   *
   * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
   */
  async chatBskyConvoDeleteMessageForSelf(
    request: operations.ChatBskyConvoDeleteMessageForSelfRequestBody,
    options?: RequestOptions,
  ): Promise<components.ChatBskyConvoDefsDeletedMessageView> {
    return unwrapAsync(chatBskyConvoChatBskyConvoDeleteMessageForSelf(
      this,
      request,
      options,
    ));
  }

  /**
   * *This endpoint is part of the Bluesky Chat (DMs) APIs. Requests usually require authentication, are directed to the user's PDS intance, and proxied to the single central chat service by setting the appropriate service DID (`did:web:api.bsky.chat`) in the service proxying header.*
   *
   * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
   */
  async chatBskyConvoGetConvo(
    request: operations.ChatBskyConvoGetConvoRequest,
    options?: RequestOptions,
  ): Promise<operations.ChatBskyConvoGetConvoResponseBody> {
    return unwrapAsync(chatBskyConvoChatBskyConvoGetConvo(
      this,
      request,
      options,
    ));
  }

  /**
   * *This endpoint is part of the Bluesky Chat (DMs) APIs. Requests usually require authentication, are directed to the user's PDS intance, and proxied to the single central chat service by setting the appropriate service DID (`did:web:api.bsky.chat`) in the service proxying header.*
   *
   * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
   */
  async chatBskyConvoGetConvoForMembers(
    request: operations.ChatBskyConvoGetConvoForMembersRequest,
    options?: RequestOptions,
  ): Promise<operations.ChatBskyConvoGetConvoForMembersResponseBody> {
    return unwrapAsync(chatBskyConvoChatBskyConvoGetConvoForMembers(
      this,
      request,
      options,
    ));
  }

  /**
   * *This endpoint is part of the Bluesky Chat (DMs) APIs. Requests usually require authentication, are directed to the user's PDS intance, and proxied to the single central chat service by setting the appropriate service DID (`did:web:api.bsky.chat`) in the service proxying header.*
   *
   * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
   */
  async chatBskyConvoGetLog(
    request?: operations.ChatBskyConvoGetLogRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ChatBskyConvoGetLogResponseBody> {
    return unwrapAsync(chatBskyConvoChatBskyConvoGetLog(
      this,
      request,
      options,
    ));
  }

  /**
   * *This endpoint is part of the Bluesky Chat (DMs) APIs. Requests usually require authentication, are directed to the user's PDS intance, and proxied to the single central chat service by setting the appropriate service DID (`did:web:api.bsky.chat`) in the service proxying header.*
   *
   * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
   */
  async chatBskyConvoGetMessages(
    request: operations.ChatBskyConvoGetMessagesRequest,
    options?: RequestOptions,
  ): Promise<operations.ChatBskyConvoGetMessagesResponseBody> {
    return unwrapAsync(chatBskyConvoChatBskyConvoGetMessages(
      this,
      request,
      options,
    ));
  }

  /**
   * *This endpoint is part of the Bluesky Chat (DMs) APIs. Requests usually require authentication, are directed to the user's PDS intance, and proxied to the single central chat service by setting the appropriate service DID (`did:web:api.bsky.chat`) in the service proxying header.*
   *
   * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
   */
  async chatBskyConvoLeaveConvo(
    request: operations.ChatBskyConvoLeaveConvoRequestBody,
    options?: RequestOptions,
  ): Promise<operations.ChatBskyConvoLeaveConvoResponseBody> {
    return unwrapAsync(chatBskyConvoChatBskyConvoLeaveConvo(
      this,
      request,
      options,
    ));
  }

  /**
   * *This endpoint is part of the Bluesky Chat (DMs) APIs. Requests usually require authentication, are directed to the user's PDS intance, and proxied to the single central chat service by setting the appropriate service DID (`did:web:api.bsky.chat`) in the service proxying header.*
   *
   * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
   */
  async chatBskyConvoListConvos(
    request?: operations.ChatBskyConvoListConvosRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ChatBskyConvoListConvosResponseBody> {
    return unwrapAsync(chatBskyConvoChatBskyConvoListConvos(
      this,
      request,
      options,
    ));
  }

  /**
   * *This endpoint is part of the Bluesky Chat (DMs) APIs. Requests usually require authentication, are directed to the user's PDS intance, and proxied to the single central chat service by setting the appropriate service DID (`did:web:api.bsky.chat`) in the service proxying header.*
   *
   * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
   */
  async chatBskyConvoMuteConvo(
    request: operations.ChatBskyConvoMuteConvoRequestBody,
    options?: RequestOptions,
  ): Promise<operations.ChatBskyConvoMuteConvoResponseBody> {
    return unwrapAsync(chatBskyConvoChatBskyConvoMuteConvo(
      this,
      request,
      options,
    ));
  }

  /**
   * *This endpoint is part of the Bluesky Chat (DMs) APIs. Requests usually require authentication, are directed to the user's PDS intance, and proxied to the single central chat service by setting the appropriate service DID (`did:web:api.bsky.chat`) in the service proxying header.*
   *
   * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
   */
  async chatBskyConvoSendMessage(
    request: operations.ChatBskyConvoSendMessageRequestBody,
    options?: RequestOptions,
  ): Promise<components.ChatBskyConvoDefsMessageView> {
    return unwrapAsync(chatBskyConvoChatBskyConvoSendMessage(
      this,
      request,
      options,
    ));
  }

  /**
   * *This endpoint is part of the Bluesky Chat (DMs) APIs. Requests usually require authentication, are directed to the user's PDS intance, and proxied to the single central chat service by setting the appropriate service DID (`did:web:api.bsky.chat`) in the service proxying header.*
   *
   * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
   */
  async chatBskyConvoSendMessageBatch(
    request: operations.ChatBskyConvoSendMessageBatchRequestBody,
    options?: RequestOptions,
  ): Promise<operations.ChatBskyConvoSendMessageBatchResponseBody> {
    return unwrapAsync(chatBskyConvoChatBskyConvoSendMessageBatch(
      this,
      request,
      options,
    ));
  }

  /**
   * *This endpoint is part of the Bluesky Chat (DMs) APIs. Requests usually require authentication, are directed to the user's PDS intance, and proxied to the single central chat service by setting the appropriate service DID (`did:web:api.bsky.chat`) in the service proxying header.*
   *
   * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
   */
  async chatBskyConvoUnmuteConvo(
    request: operations.ChatBskyConvoUnmuteConvoRequestBody,
    options?: RequestOptions,
  ): Promise<operations.ChatBskyConvoUnmuteConvoResponseBody> {
    return unwrapAsync(chatBskyConvoChatBskyConvoUnmuteConvo(
      this,
      request,
      options,
    ));
  }

  /**
   * *This endpoint is part of the Bluesky Chat (DMs) APIs. Requests usually require authentication, are directed to the user's PDS intance, and proxied to the single central chat service by setting the appropriate service DID (`did:web:api.bsky.chat`) in the service proxying header.*
   *
   * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
   */
  async chatBskyConvoUpdateRead(
    request: operations.ChatBskyConvoUpdateReadRequestBody,
    options?: RequestOptions,
  ): Promise<operations.ChatBskyConvoUpdateReadResponseBody> {
    return unwrapAsync(chatBskyConvoChatBskyConvoUpdateRead(
      this,
      request,
      options,
    ));
  }
}
