/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { toolsOzoneSettingToolsOzoneSettingListOptions } from "../funcs/toolsOzoneSettingToolsOzoneSettingListOptions.js";
import { toolsOzoneSettingToolsOzoneSettingRemoveOptions } from "../funcs/toolsOzoneSettingToolsOzoneSettingRemoveOptions.js";
import { toolsOzoneSettingToolsOzoneSettingUpsertOption } from "../funcs/toolsOzoneSettingToolsOzoneSettingUpsertOption.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Setting extends ClientSDK {
  /**
   * *This endpoint is part of the [Ozone moderation service](https://ozone.tools/) APIs. Requests usually require authentication, are directed to the user's PDS intance, and proxied to the Ozone instance indicated by the DID in the service proxying header. Admin authenentication may also be possible, with request sent directly to the Ozone instance.*
   *
   * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
   *
   * List settings with optional filtering
   */
  async toolsOzoneSettingListOptions(
    request: operations.ToolsOzoneSettingListOptionsRequest,
    options?: RequestOptions,
  ): Promise<operations.ToolsOzoneSettingListOptionsResponseBody> {
    return unwrapAsync(toolsOzoneSettingToolsOzoneSettingListOptions(
      this,
      request,
      options,
    ));
  }

  /**
   * *This endpoint is part of the [Ozone moderation service](https://ozone.tools/) APIs. Requests usually require authentication, are directed to the user's PDS intance, and proxied to the Ozone instance indicated by the DID in the service proxying header. Admin authenentication may also be possible, with request sent directly to the Ozone instance.*
   *
   * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
   *
   * Delete settings by key
   */
  async toolsOzoneSettingRemoveOptions(
    request: operations.ToolsOzoneSettingRemoveOptionsRequestBody,
    options?: RequestOptions,
  ): Promise<operations.ToolsOzoneSettingRemoveOptionsResponseBody> {
    return unwrapAsync(toolsOzoneSettingToolsOzoneSettingRemoveOptions(
      this,
      request,
      options,
    ));
  }

  /**
   * *This endpoint is part of the [Ozone moderation service](https://ozone.tools/) APIs. Requests usually require authentication, are directed to the user's PDS intance, and proxied to the Ozone instance indicated by the DID in the service proxying header. Admin authenentication may also be possible, with request sent directly to the Ozone instance.*
   *
   * *To learn more about calling atproto API endpoints like this one, see the [API Hosts and Auth](/docs/advanced-guides/api-directory) guide.*
   *
   * Create or update setting option
   */
  async toolsOzoneSettingUpsertOption(
    request: operations.ToolsOzoneSettingUpsertOptionRequestBody,
    options?: RequestOptions,
  ): Promise<operations.ToolsOzoneSettingUpsertOptionResponseBody> {
    return unwrapAsync(toolsOzoneSettingToolsOzoneSettingUpsertOption(
      this,
      request,
      options,
    ));
  }
}
