workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    OAS:
        inputs:
            - location: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/bluesky/bluesky/-oas
targets:
    bluesky:
        target: typescript
        source: OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/bluesky/bluesky/-oas-typescript-code-samples
            blocking: false
