/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AppBskyGraphGetStarterPacksRequest = {
  uris: Array<string>;
};

/**
 * OK
 */
export type AppBskyGraphGetStarterPacksResponse = {
  starterPacks: Array<components.AppBskyGraphDefsStarterPackViewBasic>;
};

/** @internal */
export const AppBskyGraphGetStarterPacksRequest$inboundSchema: z.ZodType<
  AppBskyGraphGetStarterPacksRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uris: z.array(z.string()),
});

/** @internal */
export type AppBskyGraphGetStarterPacksRequest$Outbound = {
  uris: Array<string>;
};

/** @internal */
export const AppBskyGraphGetStarterPacksRequest$outboundSchema: z.ZodType<
  AppBskyGraphGetStarterPacksRequest$Outbound,
  z.ZodTypeDef,
  AppBskyGraphGetStarterPacksRequest
> = z.object({
  uris: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphGetStarterPacksRequest$ {
  /** @deprecated use `AppBskyGraphGetStarterPacksRequest$inboundSchema` instead. */
  export const inboundSchema = AppBskyGraphGetStarterPacksRequest$inboundSchema;
  /** @deprecated use `AppBskyGraphGetStarterPacksRequest$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphGetStarterPacksRequest$outboundSchema;
  /** @deprecated use `AppBskyGraphGetStarterPacksRequest$Outbound` instead. */
  export type Outbound = AppBskyGraphGetStarterPacksRequest$Outbound;
}

export function appBskyGraphGetStarterPacksRequestToJSON(
  appBskyGraphGetStarterPacksRequest: AppBskyGraphGetStarterPacksRequest,
): string {
  return JSON.stringify(
    AppBskyGraphGetStarterPacksRequest$outboundSchema.parse(
      appBskyGraphGetStarterPacksRequest,
    ),
  );
}

export function appBskyGraphGetStarterPacksRequestFromJSON(
  jsonString: string,
): SafeParseResult<AppBskyGraphGetStarterPacksRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AppBskyGraphGetStarterPacksRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppBskyGraphGetStarterPacksRequest' from JSON`,
  );
}

/** @internal */
export const AppBskyGraphGetStarterPacksResponse$inboundSchema: z.ZodType<
  AppBskyGraphGetStarterPacksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  starterPacks: z.array(
    components.AppBskyGraphDefsStarterPackViewBasic$inboundSchema,
  ),
});

/** @internal */
export type AppBskyGraphGetStarterPacksResponse$Outbound = {
  starterPacks: Array<components.AppBskyGraphDefsStarterPackViewBasic$Outbound>;
};

/** @internal */
export const AppBskyGraphGetStarterPacksResponse$outboundSchema: z.ZodType<
  AppBskyGraphGetStarterPacksResponse$Outbound,
  z.ZodTypeDef,
  AppBskyGraphGetStarterPacksResponse
> = z.object({
  starterPacks: z.array(
    components.AppBskyGraphDefsStarterPackViewBasic$outboundSchema,
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphGetStarterPacksResponse$ {
  /** @deprecated use `AppBskyGraphGetStarterPacksResponse$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyGraphGetStarterPacksResponse$inboundSchema;
  /** @deprecated use `AppBskyGraphGetStarterPacksResponse$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyGraphGetStarterPacksResponse$outboundSchema;
  /** @deprecated use `AppBskyGraphGetStarterPacksResponse$Outbound` instead. */
  export type Outbound = AppBskyGraphGetStarterPacksResponse$Outbound;
}

export function appBskyGraphGetStarterPacksResponseToJSON(
  appBskyGraphGetStarterPacksResponse: AppBskyGraphGetStarterPacksResponse,
): string {
  return JSON.stringify(
    AppBskyGraphGetStarterPacksResponse$outboundSchema.parse(
      appBskyGraphGetStarterPacksResponse,
    ),
  );
}

export function appBskyGraphGetStarterPacksResponseFromJSON(
  jsonString: string,
): SafeParseResult<AppBskyGraphGetStarterPacksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AppBskyGraphGetStarterPacksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppBskyGraphGetStarterPacksResponse' from JSON`,
  );
}
