/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AppBskyActorPutPreferencesRequestBody = {
  preferences: Array<components.AppBskyActorDefsPreferences>;
};

/** @internal */
export const AppBskyActorPutPreferencesRequestBody$inboundSchema: z.ZodType<
  AppBskyActorPutPreferencesRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  preferences: z.array(components.AppBskyActorDefsPreferences$inboundSchema),
});

/** @internal */
export type AppBskyActorPutPreferencesRequestBody$Outbound = {
  preferences: Array<components.AppBskyActorDefsPreferences$Outbound>;
};

/** @internal */
export const AppBskyActorPutPreferencesRequestBody$outboundSchema: z.ZodType<
  AppBskyActorPutPreferencesRequestBody$Outbound,
  z.ZodTypeDef,
  AppBskyActorPutPreferencesRequestBody
> = z.object({
  preferences: z.array(components.AppBskyActorDefsPreferences$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyActorPutPreferencesRequestBody$ {
  /** @deprecated use `AppBskyActorPutPreferencesRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyActorPutPreferencesRequestBody$inboundSchema;
  /** @deprecated use `AppBskyActorPutPreferencesRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyActorPutPreferencesRequestBody$outboundSchema;
  /** @deprecated use `AppBskyActorPutPreferencesRequestBody$Outbound` instead. */
  export type Outbound = AppBskyActorPutPreferencesRequestBody$Outbound;
}

export function appBskyActorPutPreferencesRequestBodyToJSON(
  appBskyActorPutPreferencesRequestBody: AppBskyActorPutPreferencesRequestBody,
): string {
  return JSON.stringify(
    AppBskyActorPutPreferencesRequestBody$outboundSchema.parse(
      appBskyActorPutPreferencesRequestBody,
    ),
  );
}

export function appBskyActorPutPreferencesRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<AppBskyActorPutPreferencesRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AppBskyActorPutPreferencesRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppBskyActorPutPreferencesRequestBody' from JSON`,
  );
}
