/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AppBskyFeedGetLikesRequest = {
  /**
   * AT-URI of the subject (eg, a post record).
   */
  uri: string;
  /**
   * CID of the subject record (aka, specific version of record), to filter likes.
   */
  cid?: string | undefined;
  limit?: number | undefined;
  cursor?: string | undefined;
};

/**
 * OK
 */
export type AppBskyFeedGetLikesResponseBody = {
  uri: string;
  cid?: string | undefined;
  cursor?: string | undefined;
  likes: Array<components.AppBskyFeedGetLikesLike>;
};

/** @internal */
export const AppBskyFeedGetLikesRequest$inboundSchema: z.ZodType<
  AppBskyFeedGetLikesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uri: z.string(),
  cid: z.string().optional(),
  limit: z.number().int().default(50),
  cursor: z.string().optional(),
});

/** @internal */
export type AppBskyFeedGetLikesRequest$Outbound = {
  uri: string;
  cid?: string | undefined;
  limit: number;
  cursor?: string | undefined;
};

/** @internal */
export const AppBskyFeedGetLikesRequest$outboundSchema: z.ZodType<
  AppBskyFeedGetLikesRequest$Outbound,
  z.ZodTypeDef,
  AppBskyFeedGetLikesRequest
> = z.object({
  uri: z.string(),
  cid: z.string().optional(),
  limit: z.number().int().default(50),
  cursor: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyFeedGetLikesRequest$ {
  /** @deprecated use `AppBskyFeedGetLikesRequest$inboundSchema` instead. */
  export const inboundSchema = AppBskyFeedGetLikesRequest$inboundSchema;
  /** @deprecated use `AppBskyFeedGetLikesRequest$outboundSchema` instead. */
  export const outboundSchema = AppBskyFeedGetLikesRequest$outboundSchema;
  /** @deprecated use `AppBskyFeedGetLikesRequest$Outbound` instead. */
  export type Outbound = AppBskyFeedGetLikesRequest$Outbound;
}

export function appBskyFeedGetLikesRequestToJSON(
  appBskyFeedGetLikesRequest: AppBskyFeedGetLikesRequest,
): string {
  return JSON.stringify(
    AppBskyFeedGetLikesRequest$outboundSchema.parse(appBskyFeedGetLikesRequest),
  );
}

export function appBskyFeedGetLikesRequestFromJSON(
  jsonString: string,
): SafeParseResult<AppBskyFeedGetLikesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppBskyFeedGetLikesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppBskyFeedGetLikesRequest' from JSON`,
  );
}

/** @internal */
export const AppBskyFeedGetLikesResponseBody$inboundSchema: z.ZodType<
  AppBskyFeedGetLikesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  uri: z.string(),
  cid: z.string().optional(),
  cursor: z.string().optional(),
  likes: z.array(components.AppBskyFeedGetLikesLike$inboundSchema),
});

/** @internal */
export type AppBskyFeedGetLikesResponseBody$Outbound = {
  uri: string;
  cid?: string | undefined;
  cursor?: string | undefined;
  likes: Array<components.AppBskyFeedGetLikesLike$Outbound>;
};

/** @internal */
export const AppBskyFeedGetLikesResponseBody$outboundSchema: z.ZodType<
  AppBskyFeedGetLikesResponseBody$Outbound,
  z.ZodTypeDef,
  AppBskyFeedGetLikesResponseBody
> = z.object({
  uri: z.string(),
  cid: z.string().optional(),
  cursor: z.string().optional(),
  likes: z.array(components.AppBskyFeedGetLikesLike$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyFeedGetLikesResponseBody$ {
  /** @deprecated use `AppBskyFeedGetLikesResponseBody$inboundSchema` instead. */
  export const inboundSchema = AppBskyFeedGetLikesResponseBody$inboundSchema;
  /** @deprecated use `AppBskyFeedGetLikesResponseBody$outboundSchema` instead. */
  export const outboundSchema = AppBskyFeedGetLikesResponseBody$outboundSchema;
  /** @deprecated use `AppBskyFeedGetLikesResponseBody$Outbound` instead. */
  export type Outbound = AppBskyFeedGetLikesResponseBody$Outbound;
}

export function appBskyFeedGetLikesResponseBodyToJSON(
  appBskyFeedGetLikesResponseBody: AppBskyFeedGetLikesResponseBody,
): string {
  return JSON.stringify(
    AppBskyFeedGetLikesResponseBody$outboundSchema.parse(
      appBskyFeedGetLikesResponseBody,
    ),
  );
}

export function appBskyFeedGetLikesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<AppBskyFeedGetLikesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppBskyFeedGetLikesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppBskyFeedGetLikesResponseBody' from JSON`,
  );
}
