/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AppBskyFeedGetPostsRequest = {
  /**
   * List of post AT-URIs to return hydrated views for.
   */
  uris: Array<string>;
};

/**
 * OK
 */
export type AppBskyFeedGetPostsResponseBody = {
  posts: Array<components.AppBskyFeedDefsPostView>;
};

/** @internal */
export const AppBskyFeedGetPostsRequest$inboundSchema: z.ZodType<
  AppBskyFeedGetPostsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uris: z.array(z.string()),
});

/** @internal */
export type AppBskyFeedGetPostsRequest$Outbound = {
  uris: Array<string>;
};

/** @internal */
export const AppBskyFeedGetPostsRequest$outboundSchema: z.ZodType<
  AppBskyFeedGetPostsRequest$Outbound,
  z.ZodTypeDef,
  AppBskyFeedGetPostsRequest
> = z.object({
  uris: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyFeedGetPostsRequest$ {
  /** @deprecated use `AppBskyFeedGetPostsRequest$inboundSchema` instead. */
  export const inboundSchema = AppBskyFeedGetPostsRequest$inboundSchema;
  /** @deprecated use `AppBskyFeedGetPostsRequest$outboundSchema` instead. */
  export const outboundSchema = AppBskyFeedGetPostsRequest$outboundSchema;
  /** @deprecated use `AppBskyFeedGetPostsRequest$Outbound` instead. */
  export type Outbound = AppBskyFeedGetPostsRequest$Outbound;
}

export function appBskyFeedGetPostsRequestToJSON(
  appBskyFeedGetPostsRequest: AppBskyFeedGetPostsRequest,
): string {
  return JSON.stringify(
    AppBskyFeedGetPostsRequest$outboundSchema.parse(appBskyFeedGetPostsRequest),
  );
}

export function appBskyFeedGetPostsRequestFromJSON(
  jsonString: string,
): SafeParseResult<AppBskyFeedGetPostsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppBskyFeedGetPostsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppBskyFeedGetPostsRequest' from JSON`,
  );
}

/** @internal */
export const AppBskyFeedGetPostsResponseBody$inboundSchema: z.ZodType<
  AppBskyFeedGetPostsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  posts: z.array(components.AppBskyFeedDefsPostView$inboundSchema),
});

/** @internal */
export type AppBskyFeedGetPostsResponseBody$Outbound = {
  posts: Array<components.AppBskyFeedDefsPostView$Outbound>;
};

/** @internal */
export const AppBskyFeedGetPostsResponseBody$outboundSchema: z.ZodType<
  AppBskyFeedGetPostsResponseBody$Outbound,
  z.ZodTypeDef,
  AppBskyFeedGetPostsResponseBody
> = z.object({
  posts: z.array(components.AppBskyFeedDefsPostView$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyFeedGetPostsResponseBody$ {
  /** @deprecated use `AppBskyFeedGetPostsResponseBody$inboundSchema` instead. */
  export const inboundSchema = AppBskyFeedGetPostsResponseBody$inboundSchema;
  /** @deprecated use `AppBskyFeedGetPostsResponseBody$outboundSchema` instead. */
  export const outboundSchema = AppBskyFeedGetPostsResponseBody$outboundSchema;
  /** @deprecated use `AppBskyFeedGetPostsResponseBody$Outbound` instead. */
  export type Outbound = AppBskyFeedGetPostsResponseBody$Outbound;
}

export function appBskyFeedGetPostsResponseBodyToJSON(
  appBskyFeedGetPostsResponseBody: AppBskyFeedGetPostsResponseBody,
): string {
  return JSON.stringify(
    AppBskyFeedGetPostsResponseBody$outboundSchema.parse(
      appBskyFeedGetPostsResponseBody,
    ),
  );
}

export function appBskyFeedGetPostsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<AppBskyFeedGetPostsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppBskyFeedGetPostsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppBskyFeedGetPostsResponseBody' from JSON`,
  );
}
