/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ComAtprotoServerRevokeAppPasswordBody = {
  name: string;
};

/** @internal */
export const ComAtprotoServerRevokeAppPasswordBody$inboundSchema: z.ZodType<
  ComAtprotoServerRevokeAppPasswordBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});

/** @internal */
export type ComAtprotoServerRevokeAppPasswordBody$Outbound = {
  name: string;
};

/** @internal */
export const ComAtprotoServerRevokeAppPasswordBody$outboundSchema: z.ZodType<
  ComAtprotoServerRevokeAppPasswordBody$Outbound,
  z.ZodTypeDef,
  ComAtprotoServerRevokeAppPasswordBody
> = z.object({
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComAtprotoServerRevokeAppPasswordBody$ {
  /** @deprecated use `ComAtprotoServerRevokeAppPasswordBody$inboundSchema` instead. */
  export const inboundSchema =
    ComAtprotoServerRevokeAppPasswordBody$inboundSchema;
  /** @deprecated use `ComAtprotoServerRevokeAppPasswordBody$outboundSchema` instead. */
  export const outboundSchema =
    ComAtprotoServerRevokeAppPasswordBody$outboundSchema;
  /** @deprecated use `ComAtprotoServerRevokeAppPasswordBody$Outbound` instead. */
  export type Outbound = ComAtprotoServerRevokeAppPasswordBody$Outbound;
}

export function comAtprotoServerRevokeAppPasswordBodyToJSON(
  comAtprotoServerRevokeAppPasswordBody: ComAtprotoServerRevokeAppPasswordBody,
): string {
  return JSON.stringify(
    ComAtprotoServerRevokeAppPasswordBody$outboundSchema.parse(
      comAtprotoServerRevokeAppPasswordBody,
    ),
  );
}

export function comAtprotoServerRevokeAppPasswordBodyFromJSON(
  jsonString: string,
): SafeParseResult<ComAtprotoServerRevokeAppPasswordBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ComAtprotoServerRevokeAppPasswordBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ComAtprotoServerRevokeAppPasswordBody' from JSON`,
  );
}
