/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ComAtprotoServerUpdateEmailRequest = {
  email: string;
  emailAuthFactor?: boolean | undefined;
  /**
   * Requires a token from com.atproto.sever.requestEmailUpdate if the account's email has been confirmed.
   */
  token?: string | undefined;
};

/** @internal */
export const ComAtprotoServerUpdateEmailRequest$inboundSchema: z.ZodType<
  ComAtprotoServerUpdateEmailRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string(),
  emailAuthFactor: z.boolean().optional(),
  token: z.string().optional(),
});

/** @internal */
export type ComAtprotoServerUpdateEmailRequest$Outbound = {
  email: string;
  emailAuthFactor?: boolean | undefined;
  token?: string | undefined;
};

/** @internal */
export const ComAtprotoServerUpdateEmailRequest$outboundSchema: z.ZodType<
  ComAtprotoServerUpdateEmailRequest$Outbound,
  z.ZodTypeDef,
  ComAtprotoServerUpdateEmailRequest
> = z.object({
  email: z.string(),
  emailAuthFactor: z.boolean().optional(),
  token: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComAtprotoServerUpdateEmailRequest$ {
  /** @deprecated use `ComAtprotoServerUpdateEmailRequest$inboundSchema` instead. */
  export const inboundSchema = ComAtprotoServerUpdateEmailRequest$inboundSchema;
  /** @deprecated use `ComAtprotoServerUpdateEmailRequest$outboundSchema` instead. */
  export const outboundSchema =
    ComAtprotoServerUpdateEmailRequest$outboundSchema;
  /** @deprecated use `ComAtprotoServerUpdateEmailRequest$Outbound` instead. */
  export type Outbound = ComAtprotoServerUpdateEmailRequest$Outbound;
}

export function comAtprotoServerUpdateEmailRequestToJSON(
  comAtprotoServerUpdateEmailRequest: ComAtprotoServerUpdateEmailRequest,
): string {
  return JSON.stringify(
    ComAtprotoServerUpdateEmailRequest$outboundSchema.parse(
      comAtprotoServerUpdateEmailRequest,
    ),
  );
}

export function comAtprotoServerUpdateEmailRequestFromJSON(
  jsonString: string,
): SafeParseResult<ComAtprotoServerUpdateEmailRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ComAtprotoServerUpdateEmailRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ComAtprotoServerUpdateEmailRequest' from JSON`,
  );
}
