/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ComAtprotoAdminDisableAccountInvitesRequest = {
  account: string;
  /**
   * Optional reason for disabled invites.
   */
  note?: string | undefined;
};

/** @internal */
export const ComAtprotoAdminDisableAccountInvitesRequest$inboundSchema:
  z.ZodType<
    ComAtprotoAdminDisableAccountInvitesRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    account: z.string(),
    note: z.string().optional(),
  });

/** @internal */
export type ComAtprotoAdminDisableAccountInvitesRequest$Outbound = {
  account: string;
  note?: string | undefined;
};

/** @internal */
export const ComAtprotoAdminDisableAccountInvitesRequest$outboundSchema:
  z.ZodType<
    ComAtprotoAdminDisableAccountInvitesRequest$Outbound,
    z.ZodTypeDef,
    ComAtprotoAdminDisableAccountInvitesRequest
  > = z.object({
    account: z.string(),
    note: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComAtprotoAdminDisableAccountInvitesRequest$ {
  /** @deprecated use `ComAtprotoAdminDisableAccountInvitesRequest$inboundSchema` instead. */
  export const inboundSchema =
    ComAtprotoAdminDisableAccountInvitesRequest$inboundSchema;
  /** @deprecated use `ComAtprotoAdminDisableAccountInvitesRequest$outboundSchema` instead. */
  export const outboundSchema =
    ComAtprotoAdminDisableAccountInvitesRequest$outboundSchema;
  /** @deprecated use `ComAtprotoAdminDisableAccountInvitesRequest$Outbound` instead. */
  export type Outbound = ComAtprotoAdminDisableAccountInvitesRequest$Outbound;
}

export function comAtprotoAdminDisableAccountInvitesRequestToJSON(
  comAtprotoAdminDisableAccountInvitesRequest:
    ComAtprotoAdminDisableAccountInvitesRequest,
): string {
  return JSON.stringify(
    ComAtprotoAdminDisableAccountInvitesRequest$outboundSchema.parse(
      comAtprotoAdminDisableAccountInvitesRequest,
    ),
  );
}

export function comAtprotoAdminDisableAccountInvitesRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  ComAtprotoAdminDisableAccountInvitesRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComAtprotoAdminDisableAccountInvitesRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComAtprotoAdminDisableAccountInvitesRequest' from JSON`,
  );
}
