/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AppBskyActorDefsProfileAssociated,
  AppBskyActorDefsProfileAssociated$inboundSchema,
  AppBskyActorDefsProfileAssociated$Outbound,
  AppBskyActorDefsProfileAssociated$outboundSchema,
} from "./appbskyactordefsprofileassociated.js";
import {
  AppBskyActorDefsViewerState,
  AppBskyActorDefsViewerState$inboundSchema,
  AppBskyActorDefsViewerState$Outbound,
  AppBskyActorDefsViewerState$outboundSchema,
} from "./appbskyactordefsviewerstate.js";
import {
  AppBskyGraphDefsStarterPackViewBasic,
  AppBskyGraphDefsStarterPackViewBasic$inboundSchema,
  AppBskyGraphDefsStarterPackViewBasic$Outbound,
  AppBskyGraphDefsStarterPackViewBasic$outboundSchema,
} from "./appbskygraphdefsstarterpackviewbasic.js";
import {
  ComAtprotoLabelDefsLabel,
  ComAtprotoLabelDefsLabel$inboundSchema,
  ComAtprotoLabelDefsLabel$Outbound,
  ComAtprotoLabelDefsLabel$outboundSchema,
} from "./comatprotolabeldefslabel.js";
import {
  ComAtprotoRepoStrongRef,
  ComAtprotoRepoStrongRef$inboundSchema,
  ComAtprotoRepoStrongRef$Outbound,
  ComAtprotoRepoStrongRef$outboundSchema,
} from "./comatprotorepostrongref.js";

export type AppBskyActorDefsProfileViewDetailed = {
  did: string;
  handle: string;
  displayName?: string | undefined;
  description?: string | undefined;
  avatar?: string | undefined;
  banner?: string | undefined;
  followersCount?: number | undefined;
  followsCount?: number | undefined;
  postsCount?: number | undefined;
  associated?: AppBskyActorDefsProfileAssociated | undefined;
  joinedViaStarterPack?: AppBskyGraphDefsStarterPackViewBasic | undefined;
  indexedAt?: Date | undefined;
  createdAt?: Date | undefined;
  /**
   * Metadata about the requesting account's relationship with the subject account. Only has meaningful content for authed requests.
   */
  viewer?: AppBskyActorDefsViewerState | undefined;
  labels?: Array<ComAtprotoLabelDefsLabel> | undefined;
  pinnedPost?: ComAtprotoRepoStrongRef | undefined;
};

/** @internal */
export const AppBskyActorDefsProfileViewDetailed$inboundSchema: z.ZodType<
  AppBskyActorDefsProfileViewDetailed,
  z.ZodTypeDef,
  unknown
> = z.object({
  did: z.string(),
  handle: z.string(),
  displayName: z.string().optional(),
  description: z.string().optional(),
  avatar: z.string().optional(),
  banner: z.string().optional(),
  followersCount: z.number().int().optional(),
  followsCount: z.number().int().optional(),
  postsCount: z.number().int().optional(),
  associated: AppBskyActorDefsProfileAssociated$inboundSchema.optional(),
  joinedViaStarterPack: AppBskyGraphDefsStarterPackViewBasic$inboundSchema
    .optional(),
  indexedAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  viewer: AppBskyActorDefsViewerState$inboundSchema.optional(),
  labels: z.array(ComAtprotoLabelDefsLabel$inboundSchema).optional(),
  pinnedPost: ComAtprotoRepoStrongRef$inboundSchema.optional(),
});

/** @internal */
export type AppBskyActorDefsProfileViewDetailed$Outbound = {
  did: string;
  handle: string;
  displayName?: string | undefined;
  description?: string | undefined;
  avatar?: string | undefined;
  banner?: string | undefined;
  followersCount?: number | undefined;
  followsCount?: number | undefined;
  postsCount?: number | undefined;
  associated?: AppBskyActorDefsProfileAssociated$Outbound | undefined;
  joinedViaStarterPack?:
    | AppBskyGraphDefsStarterPackViewBasic$Outbound
    | undefined;
  indexedAt?: string | undefined;
  createdAt?: string | undefined;
  viewer?: AppBskyActorDefsViewerState$Outbound | undefined;
  labels?: Array<ComAtprotoLabelDefsLabel$Outbound> | undefined;
  pinnedPost?: ComAtprotoRepoStrongRef$Outbound | undefined;
};

/** @internal */
export const AppBskyActorDefsProfileViewDetailed$outboundSchema: z.ZodType<
  AppBskyActorDefsProfileViewDetailed$Outbound,
  z.ZodTypeDef,
  AppBskyActorDefsProfileViewDetailed
> = z.object({
  did: z.string(),
  handle: z.string(),
  displayName: z.string().optional(),
  description: z.string().optional(),
  avatar: z.string().optional(),
  banner: z.string().optional(),
  followersCount: z.number().int().optional(),
  followsCount: z.number().int().optional(),
  postsCount: z.number().int().optional(),
  associated: AppBskyActorDefsProfileAssociated$outboundSchema.optional(),
  joinedViaStarterPack: AppBskyGraphDefsStarterPackViewBasic$outboundSchema
    .optional(),
  indexedAt: z.date().transform(v => v.toISOString()).optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  viewer: AppBskyActorDefsViewerState$outboundSchema.optional(),
  labels: z.array(ComAtprotoLabelDefsLabel$outboundSchema).optional(),
  pinnedPost: ComAtprotoRepoStrongRef$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyActorDefsProfileViewDetailed$ {
  /** @deprecated use `AppBskyActorDefsProfileViewDetailed$inboundSchema` instead. */
  export const inboundSchema =
    AppBskyActorDefsProfileViewDetailed$inboundSchema;
  /** @deprecated use `AppBskyActorDefsProfileViewDetailed$outboundSchema` instead. */
  export const outboundSchema =
    AppBskyActorDefsProfileViewDetailed$outboundSchema;
  /** @deprecated use `AppBskyActorDefsProfileViewDetailed$Outbound` instead. */
  export type Outbound = AppBskyActorDefsProfileViewDetailed$Outbound;
}

export function appBskyActorDefsProfileViewDetailedToJSON(
  appBskyActorDefsProfileViewDetailed: AppBskyActorDefsProfileViewDetailed,
): string {
  return JSON.stringify(
    AppBskyActorDefsProfileViewDetailed$outboundSchema.parse(
      appBskyActorDefsProfileViewDetailed,
    ),
  );
}

export function appBskyActorDefsProfileViewDetailedFromJSON(
  jsonString: string,
): SafeParseResult<AppBskyActorDefsProfileViewDetailed, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AppBskyActorDefsProfileViewDetailed$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppBskyActorDefsProfileViewDetailed' from JSON`,
  );
}
