/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AppBskyActorDefsProfileView,
  AppBskyActorDefsProfileView$inboundSchema,
  AppBskyActorDefsProfileView$Outbound,
  AppBskyActorDefsProfileView$outboundSchema,
} from "./appbskyactordefsprofileview.js";

export type AppBskyGraphDefsListItemView = {
  uri: string;
  subject: AppBskyActorDefsProfileView;
};

/** @internal */
export const AppBskyGraphDefsListItemView$inboundSchema: z.ZodType<
  AppBskyGraphDefsListItemView,
  z.ZodTypeDef,
  unknown
> = z.object({
  uri: z.string(),
  subject: AppBskyActorDefsProfileView$inboundSchema,
});

/** @internal */
export type AppBskyGraphDefsListItemView$Outbound = {
  uri: string;
  subject: AppBskyActorDefsProfileView$Outbound;
};

/** @internal */
export const AppBskyGraphDefsListItemView$outboundSchema: z.ZodType<
  AppBskyGraphDefsListItemView$Outbound,
  z.ZodTypeDef,
  AppBskyGraphDefsListItemView
> = z.object({
  uri: z.string(),
  subject: AppBskyActorDefsProfileView$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppBskyGraphDefsListItemView$ {
  /** @deprecated use `AppBskyGraphDefsListItemView$inboundSchema` instead. */
  export const inboundSchema = AppBskyGraphDefsListItemView$inboundSchema;
  /** @deprecated use `AppBskyGraphDefsListItemView$outboundSchema` instead. */
  export const outboundSchema = AppBskyGraphDefsListItemView$outboundSchema;
  /** @deprecated use `AppBskyGraphDefsListItemView$Outbound` instead. */
  export type Outbound = AppBskyGraphDefsListItemView$Outbound;
}

export function appBskyGraphDefsListItemViewToJSON(
  appBskyGraphDefsListItemView: AppBskyGraphDefsListItemView,
): string {
  return JSON.stringify(
    AppBskyGraphDefsListItemView$outboundSchema.parse(
      appBskyGraphDefsListItemView,
    ),
  );
}

export function appBskyGraphDefsListItemViewFromJSON(
  jsonString: string,
): SafeParseResult<AppBskyGraphDefsListItemView, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppBskyGraphDefsListItemView$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppBskyGraphDefsListItemView' from JSON`,
  );
}
