/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ComAtprotoAdminDefsThreatSignature,
  ComAtprotoAdminDefsThreatSignature$inboundSchema,
  ComAtprotoAdminDefsThreatSignature$Outbound,
  ComAtprotoAdminDefsThreatSignature$outboundSchema,
} from "./comatprotoadmindefsthreatsignature.js";
import {
  ComAtprotoServerDefsInviteCode,
  ComAtprotoServerDefsInviteCode$inboundSchema,
  ComAtprotoServerDefsInviteCode$Outbound,
  ComAtprotoServerDefsInviteCode$outboundSchema,
} from "./comatprotoserverdefsinvitecode.js";

export type ComAtprotoAdminDefsAccountView = {
  did: string;
  handle: string;
  email?: string | undefined;
  relatedRecords?: Array<any> | undefined;
  indexedAt: Date;
  invitedBy?: ComAtprotoServerDefsInviteCode | undefined;
  invites?: Array<ComAtprotoServerDefsInviteCode> | undefined;
  invitesDisabled?: boolean | undefined;
  emailConfirmedAt?: Date | undefined;
  inviteNote?: string | undefined;
  deactivatedAt?: Date | undefined;
  threatSignatures?: Array<ComAtprotoAdminDefsThreatSignature> | undefined;
};

/** @internal */
export const ComAtprotoAdminDefsAccountView$inboundSchema: z.ZodType<
  ComAtprotoAdminDefsAccountView,
  z.ZodTypeDef,
  unknown
> = z.object({
  did: z.string(),
  handle: z.string(),
  email: z.string().optional(),
  relatedRecords: z.array(z.any()).optional(),
  indexedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  invitedBy: ComAtprotoServerDefsInviteCode$inboundSchema.optional(),
  invites: z.array(ComAtprotoServerDefsInviteCode$inboundSchema).optional(),
  invitesDisabled: z.boolean().optional(),
  emailConfirmedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  inviteNote: z.string().optional(),
  deactivatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  threatSignatures: z.array(ComAtprotoAdminDefsThreatSignature$inboundSchema)
    .optional(),
});

/** @internal */
export type ComAtprotoAdminDefsAccountView$Outbound = {
  did: string;
  handle: string;
  email?: string | undefined;
  relatedRecords?: Array<any> | undefined;
  indexedAt: string;
  invitedBy?: ComAtprotoServerDefsInviteCode$Outbound | undefined;
  invites?: Array<ComAtprotoServerDefsInviteCode$Outbound> | undefined;
  invitesDisabled?: boolean | undefined;
  emailConfirmedAt?: string | undefined;
  inviteNote?: string | undefined;
  deactivatedAt?: string | undefined;
  threatSignatures?:
    | Array<ComAtprotoAdminDefsThreatSignature$Outbound>
    | undefined;
};

/** @internal */
export const ComAtprotoAdminDefsAccountView$outboundSchema: z.ZodType<
  ComAtprotoAdminDefsAccountView$Outbound,
  z.ZodTypeDef,
  ComAtprotoAdminDefsAccountView
> = z.object({
  did: z.string(),
  handle: z.string(),
  email: z.string().optional(),
  relatedRecords: z.array(z.any()).optional(),
  indexedAt: z.date().transform(v => v.toISOString()),
  invitedBy: ComAtprotoServerDefsInviteCode$outboundSchema.optional(),
  invites: z.array(ComAtprotoServerDefsInviteCode$outboundSchema).optional(),
  invitesDisabled: z.boolean().optional(),
  emailConfirmedAt: z.date().transform(v => v.toISOString()).optional(),
  inviteNote: z.string().optional(),
  deactivatedAt: z.date().transform(v => v.toISOString()).optional(),
  threatSignatures: z.array(ComAtprotoAdminDefsThreatSignature$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComAtprotoAdminDefsAccountView$ {
  /** @deprecated use `ComAtprotoAdminDefsAccountView$inboundSchema` instead. */
  export const inboundSchema = ComAtprotoAdminDefsAccountView$inboundSchema;
  /** @deprecated use `ComAtprotoAdminDefsAccountView$outboundSchema` instead. */
  export const outboundSchema = ComAtprotoAdminDefsAccountView$outboundSchema;
  /** @deprecated use `ComAtprotoAdminDefsAccountView$Outbound` instead. */
  export type Outbound = ComAtprotoAdminDefsAccountView$Outbound;
}

export function comAtprotoAdminDefsAccountViewToJSON(
  comAtprotoAdminDefsAccountView: ComAtprotoAdminDefsAccountView,
): string {
  return JSON.stringify(
    ComAtprotoAdminDefsAccountView$outboundSchema.parse(
      comAtprotoAdminDefsAccountView,
    ),
  );
}

export function comAtprotoAdminDefsAccountViewFromJSON(
  jsonString: string,
): SafeParseResult<ComAtprotoAdminDefsAccountView, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ComAtprotoAdminDefsAccountView$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ComAtprotoAdminDefsAccountView' from JSON`,
  );
}
