/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ValidationStatus = {
  Valid: "valid",
  Unknown: "unknown",
} as const;
export type ValidationStatus = ClosedEnum<typeof ValidationStatus>;

export type ComAtprotoRepoApplyWritesCreateResult = {
  uri: string;
  cid: string;
  validationStatus?: ValidationStatus | undefined;
};

/** @internal */
export const ValidationStatus$inboundSchema: z.ZodNativeEnum<
  typeof ValidationStatus
> = z.nativeEnum(ValidationStatus);

/** @internal */
export const ValidationStatus$outboundSchema: z.ZodNativeEnum<
  typeof ValidationStatus
> = ValidationStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ValidationStatus$ {
  /** @deprecated use `ValidationStatus$inboundSchema` instead. */
  export const inboundSchema = ValidationStatus$inboundSchema;
  /** @deprecated use `ValidationStatus$outboundSchema` instead. */
  export const outboundSchema = ValidationStatus$outboundSchema;
}

/** @internal */
export const ComAtprotoRepoApplyWritesCreateResult$inboundSchema: z.ZodType<
  ComAtprotoRepoApplyWritesCreateResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  uri: z.string(),
  cid: z.string(),
  validationStatus: ValidationStatus$inboundSchema.optional(),
});

/** @internal */
export type ComAtprotoRepoApplyWritesCreateResult$Outbound = {
  uri: string;
  cid: string;
  validationStatus?: string | undefined;
};

/** @internal */
export const ComAtprotoRepoApplyWritesCreateResult$outboundSchema: z.ZodType<
  ComAtprotoRepoApplyWritesCreateResult$Outbound,
  z.ZodTypeDef,
  ComAtprotoRepoApplyWritesCreateResult
> = z.object({
  uri: z.string(),
  cid: z.string(),
  validationStatus: ValidationStatus$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComAtprotoRepoApplyWritesCreateResult$ {
  /** @deprecated use `ComAtprotoRepoApplyWritesCreateResult$inboundSchema` instead. */
  export const inboundSchema =
    ComAtprotoRepoApplyWritesCreateResult$inboundSchema;
  /** @deprecated use `ComAtprotoRepoApplyWritesCreateResult$outboundSchema` instead. */
  export const outboundSchema =
    ComAtprotoRepoApplyWritesCreateResult$outboundSchema;
  /** @deprecated use `ComAtprotoRepoApplyWritesCreateResult$Outbound` instead. */
  export type Outbound = ComAtprotoRepoApplyWritesCreateResult$Outbound;
}

export function comAtprotoRepoApplyWritesCreateResultToJSON(
  comAtprotoRepoApplyWritesCreateResult: ComAtprotoRepoApplyWritesCreateResult,
): string {
  return JSON.stringify(
    ComAtprotoRepoApplyWritesCreateResult$outboundSchema.parse(
      comAtprotoRepoApplyWritesCreateResult,
    ),
  );
}

export function comAtprotoRepoApplyWritesCreateResultFromJSON(
  jsonString: string,
): SafeParseResult<ComAtprotoRepoApplyWritesCreateResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ComAtprotoRepoApplyWritesCreateResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ComAtprotoRepoApplyWritesCreateResult' from JSON`,
  );
}
