/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Op = {
  Create: "create",
  Update: "update",
  Delete: "delete",
} as const;
export type Op = ClosedEnum<typeof Op>;

/**
 * Logs lifecycle event on a record subject. Normally captured by automod from the firehose and emitted to ozone for historical tracking.
 */
export type ToolsOzoneModerationDefsRecordEvent = {
  comment?: string | undefined;
  op: Op;
  cid?: string | undefined;
  timestamp: Date;
};

/** @internal */
export const Op$inboundSchema: z.ZodNativeEnum<typeof Op> = z.nativeEnum(Op);
/** @internal */
export const Op$outboundSchema: z.ZodNativeEnum<typeof Op> = Op$inboundSchema;

/** @internal */
export const ToolsOzoneModerationDefsRecordEvent$inboundSchema: z.ZodType<
  ToolsOzoneModerationDefsRecordEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  comment: z.string().optional(),
  op: Op$inboundSchema,
  cid: z.string().optional(),
  timestamp: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});
/** @internal */
export type ToolsOzoneModerationDefsRecordEvent$Outbound = {
  comment?: string | undefined;
  op: string;
  cid?: string | undefined;
  timestamp: string;
};

/** @internal */
export const ToolsOzoneModerationDefsRecordEvent$outboundSchema: z.ZodType<
  ToolsOzoneModerationDefsRecordEvent$Outbound,
  z.ZodTypeDef,
  ToolsOzoneModerationDefsRecordEvent
> = z.object({
  comment: z.string().optional(),
  op: Op$outboundSchema,
  cid: z.string().optional(),
  timestamp: z.date().transform(v => v.toISOString()),
});

export function toolsOzoneModerationDefsRecordEventToJSON(
  toolsOzoneModerationDefsRecordEvent: ToolsOzoneModerationDefsRecordEvent,
): string {
  return JSON.stringify(
    ToolsOzoneModerationDefsRecordEvent$outboundSchema.parse(
      toolsOzoneModerationDefsRecordEvent,
    ),
  );
}
export function toolsOzoneModerationDefsRecordEventFromJSON(
  jsonString: string,
): SafeParseResult<ToolsOzoneModerationDefsRecordEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ToolsOzoneModerationDefsRecordEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToolsOzoneModerationDefsRecordEvent' from JSON`,
  );
}
