/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ToolsOzoneModerationDefsModEventAcknowledge = {
  comment?: string | undefined;
};

/** @internal */
export const ToolsOzoneModerationDefsModEventAcknowledge$inboundSchema:
  z.ZodType<
    ToolsOzoneModerationDefsModEventAcknowledge,
    z.ZodTypeDef,
    unknown
  > = z.object({
    comment: z.string().optional(),
  });
/** @internal */
export type ToolsOzoneModerationDefsModEventAcknowledge$Outbound = {
  comment?: string | undefined;
};

/** @internal */
export const ToolsOzoneModerationDefsModEventAcknowledge$outboundSchema:
  z.ZodType<
    ToolsOzoneModerationDefsModEventAcknowledge$Outbound,
    z.ZodTypeDef,
    ToolsOzoneModerationDefsModEventAcknowledge
  > = z.object({
    comment: z.string().optional(),
  });

export function toolsOzoneModerationDefsModEventAcknowledgeToJSON(
  toolsOzoneModerationDefsModEventAcknowledge:
    ToolsOzoneModerationDefsModEventAcknowledge,
): string {
  return JSON.stringify(
    ToolsOzoneModerationDefsModEventAcknowledge$outboundSchema.parse(
      toolsOzoneModerationDefsModEventAcknowledge,
    ),
  );
}
export function toolsOzoneModerationDefsModEventAcknowledgeFromJSON(
  jsonString: string,
): SafeParseResult<
  ToolsOzoneModerationDefsModEventAcknowledge,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ToolsOzoneModerationDefsModEventAcknowledge$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ToolsOzoneModerationDefsModEventAcknowledge' from JSON`,
  );
}
